### ISSUE TITLE
Error when committing without "author"

### ISSUE THREAD

**Issue by juancampa** [isomorphic-git/isomorphic-git#107]
In the [documentation](https://isomorphic-git.github.io/docs/commit.html) `author` doesn't appear as required for `commit` but this error is thrown:

```
models.js:440 Uncaught (in promise) TypeError: Cannot read property '_named' of undefined
    at isNamedSection (models.js:440)
    at GitConfig.get (models.js:460)
    at config (commands.js:135)
```

The error goes away if I specify `author`.

My guess is that all commits must have an author so it should be marked as required.

**Comment by juancampa** [comment]
I guess it's not required because you can also set it using `config`. Maybe the "fix" is to document this behavior. @wmhilton let me know what you think is best and I can post a PR

**Comment by wmhilton** [comment]
> I guess it's not required because you can also set it using `config`. 

That's exactly it. I think the fix will actually be to throw a better error. I'm guessing it's throwing that error because it can't find a "user" section in the config. @TomasHubelbauer actually has a PR to fix a problem in the config parser, so once I merge that, I'll fix this, and then the config should just return undefined instead of throwing an error, and then I'll add a check to make sure that author.name && author.email are not undefined, and if THAT is the case, throw a nice "Author name and email must be specified as an argument or in the .git/config file" error.

**Comment by wmhilton** [comment]
@TomasHubelbauer @juancampa In lieu of writing a CONTRIBUTING document, I slapped together a blog post: https://isomorphic-git.github.io/blog/2018/04/02/contributing-workflow.html Let me know what you think! I'll take your leftover questions and use them to write a proper CONTRIBUTING guide in the near future.

**Comment by TomasHubelbauer** [comment]
Thanks, that's much appreciated, I'll review and comment tomorrowish.

**Comment by wmhilton** [comment]
Yeah, I've noticed that on my laptop, but not on my desktop. (I develop on Windows 10 as my primary OS.)
I think it just "happens" to work in Git Bash because it creates a virtual link from `/tmp` to `%TEMP%`.

I'll drop a PR at https://github.com/Thinkmill/jest-fixtures
