### ISSUE TITLE
Gradually rewrite this project in TypeScript?

### ISSUE THREAD

**Issue by KSXGitHub** [isomorphic-git/isomorphic-git#1072]
## Rationale

1. Recent releases do not work well with TypeScript. This delays TypeScript users from upgrading isomorphic-git.

2. This project is written JavaScript with JSDoc for types.

## Suggestion

1. TypeScript supports type-checking JavaScript files with JSDoc comments, we should use it to check existing JavaScript files.

2. New files should be written in TypeScript with TSDoc comments.

3. Existing files should be slowly converted to TypeScript.

**Comment by wmhilton** [comment]
Releases 1.0.0-1.1.1 were a fluke. That `index.d.ts` file was generated by TypeScript itself, works perfectly fine with `ts-loader` and `babel-typescript`, and _all_ of the tests and JSDoc example code is typechecked by `tsc`. And I used it for weeks before and in projects that use plain `tsc` to compile as well. Honestly, I do not know why TypeScript let me down and decided to complain about the `index.d.ts` file it wrote itself.

I will not be writing MORE of my project in TypeScript, since it created this problem lol.

I _will_ continue adding `// @ts-check` to more and more of the JS files (already all the files in `src/api` are typechecked).

But _TypeScript cannot save you_. Re-writing code in TS will not fix all the problems.
