### ISSUE TITLE
MissingNameError when using pull

### ISSUE THREAD

**Issue by AxelTerizaki** [isomorphic-git/isomorphic-git#1073]
Hello.

I'm running on Node with isomorphic-git 1.1.2.

I'm trying to do a pull on an existing repository, but it errors out on me with the following message : 

```
MissingNameError: No name was provided for author in the argument or in the .git
/config file.
    at pull (C:\dev\karaokemugen-app\node_modules\isomorphic-git\index.cjs:10027
:24)
    at async gitUpdate (C:\dev\karaokemugen-app\dist\utils\git.js:51:17) {
  caller: 'git.pull',
  name: 'MissingNameError',
  code: 'MissingNameError',
  data: { role: 'author' }
}
```

I'm not using any specific config because I'm using the module to keep a repo updated (so no commit/pushes).

It worked without needing a name before 1.x.

Here's my code : 
```
await pull({
  fs: fs,
  http: http,
  dir: o.gitDir
});
```

I'm wondering why I would need to configure an author name to do a pull? Not that it's a big issue, but that might be a bug so I'm reporting it.  :)

**Comment by wmhilton** [comment]
Git pull is basically an alias for git fetch + git merge. So when you do a pull, there's a possibility you will need to make a merge commit. Hence the need to specify an author just like with git commit.

If you're... Oh, I was going to say if you specify `fastForwardOnly: true` then you won't get that error, but hmm, that's not true. It always checks. Possibly because `fastForwardOnly` could be dynamic? 🤔 What I don't want is someone's code to compile and work most of the time, but then not work in production in a hard-to-debug special case. I *think* it's fair to say that `fastForwardOnly` is likely to be hard-coded, so if it's true during development it'll be true in production. Alternatively, I guess I could make a new `fastForward` pull command... that would make sure it's hard-coded. 🤔

For now, just add `{ author: { name: "foo" }, fastForwardOnly: true }` 😁 It won't use the author if it doesn't make a merge commit so it doesn't matter what the name is.

**Comment by AxelTerizaki** [comment]
That's exactly what I did, I added an author objet, just didn't specify fastForwardOnly. 

Since my app isn't making any commits, there is no possibility of a merge happening anyway :)

**Comment by wmhilton** [comment]
Since this is a pretty common scenario, I'm adding a `fastForward` function. It's just like pull with `fastForward: true`, but it doesn't require an author.

**Comment by wmhilton** [comment]
In hindsight, letting you leave the `author` param of `commit`, `pull`, etc empty and automatically looking it up for you in `.git/config` probably wasn't a great idea either. You live you learn. Maybe in isomorphic-git 2.0 I'll have a `git.findAuthor` command to let you explicitly grab it from a config file.
