### ISSUE TITLE
statusMatrix doesn't process .gitignore

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#1076]
Using Node, no bundler.

`statusMatrix` returns files matched by `.gitignore` as `0, 2, 0` (new, untracked).

The underlying problem is that an unwrapped `fs` instance is passed to `GitIgnoreManager.isIgnored`

**Comment by wmhilton** [comment]
Ah I'm so sorry for the regression! (Hmm... Maybe I _should_ switch to TypeScript?) Love that you also added a test!

**Comment by crutchcorn** [comment]
If you'd like help migrating things to TypeScript, I'd love to assist in migration. That said, it might not catch something like this, and it'd be understandable if you wanted to keep moving forward with vanilla JS

**Comment by wmhilton** [comment]
@crutchcorn I think the best path forward is to use JSDoc internally, and keep adding `// @ts-check` at the top of more files.

`src/api/readObject.js` _is_ actually type-checked... but since `src/storage/readObject.js` doesn't have a JSDoc return signature, the result ended up being `any`. So it didn't catch the fact that `.entries` doesn't belong. We'd need to turn on the `noImplicitAny` to catch it I think, and _that_ would require lots more types everywhere.

**Comment by stefan-guggisberg** [comment]
fixed via #1077
