### ISSUE TITLE
Is it possible to get newer logs from all branches at once?

### ISSUE THREAD

**Issue by navratill** [isomorphic-git/isomorphic-git#1084]
Hi, I am using the isomorphic-git in node and I would like to read all changes on any remote branch from the local HEAD, is it possible, or do I have to do it for every single branch, it would mean:
- get list of remote branches
- fetch from every remote branch
- log from every remote branch by using branch newest commit id as ref in git.log

Is that correct steps? Thank you ✌️

**Comment by wmhilton** [comment]
You should be able to skip the middle step:
- fetch from every remote branch

`fetch` without the `singleBranch` argument fetches all the branches - it just doesn't check them out. To list the commits from a branch that hasn't been checked out, you should be able to use `log` with the remote name, like so:

```js
let remote = 'origin';
let branches = await git.listBranches({ fs, dir, remote })
for (const branch of branches) {
  commits = await git.log({ fs, dir, ref: `remotes/${remote}/${branch}` })
}
```

Limiting `log` to just the commits made after the local HEAD is a little trickier. We should probably add an `exclude` option (similar to how shallow fetch works) so that you can tell `log` to stop when it reaches a given commit(s). 🤔  As it is, you'll end up with the whole history each time.......

You can _kind_ of cheat and use `since` with the time of the local HEAD to limit the depth. Also, if the performance is really bad, you can use `depth: 10` and check to see if that includes the HEAD commit, and keep doubling the depth until you have enough. Or you can use `readCommit` manually to walk backwards through the commits...

Let me know if an `exclude` (type `string[]`, list of SHA-1 commit ids to stop at) parameter to `log` would be helpful? I think it would be pretty trivial to add, I could squeeze that in this evening. :)

**Comment by navratill** [comment]
I just wanted to assure myself, that I have to take log from every branch separately. So far since it is exactly what I need, or I can use the pagination over the depth, it is no problem so much. 

What I am more worried, is that you have to take log per branch, I would like to take just recent logs across all branches and to do it overall branches manually looks slow, but I will give it a shot.. Thanks

**Comment by wmhilton** [comment]
>  I would like to take just recent logs across all branches and to do it overall branches manually looks slow

🤔 I don't think it'll be too slow. There's no secret shortcut to getting "all the commits newer than X" - the only way is to iterate over all the remote heads and walk backwards. Ya might be able to speed it up a bit doing it in parallel:

```js
let remote = 'origin';
let branches = await git.listBranches({ fs, dir, remote })
let allcommits = await Promise.all(branches.map(
  branch => git.log({ fs, dir, since, ref: `remotes/${remote}/${branch}` })
))
```

**Comment by navratill** [comment]
thanks 👍
