### ISSUE TITLE
Tests say Success: null ms - a problem?

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#110]
Hey, maybe this is just my confusion, but most (all?) tests running in SauceLabs seem to be returning `null` for the runtime value in ms. I meant to take a look at a [random session](https://saucelabs.com/beta/tests/5609b54cd7fc48c98c72b87eedf05f2a/watch) from my latest PR, but the video doesn't load for me to be able to check on whether the execution goes through okay. Are there any more tools that could be used to verify nothing is amiss?

**Comment by wmhilton** [comment]
I noticed this happening even locally today. I think it may be a bug in the reporter.

**Comment by wmhilton** [comment]
Being resolved over yonder: https://github.com/karma-runner/karma-jasmine/pull/197

**Comment by wmhilton** [comment]
I'm closing this for now, simply because when the upstream module merges the fix and that fix makes it into a release, @greenkeeperio-bot will create a PR to update our package.json, and then we'll be running the latest version of `karma-jasmine` and the issue will be fixed. That's the fastest we could possibly fix it anyway, short of forking karma-jasmine and patching it ourselves, which seems very silly.

**Comment by wmhilton** [comment]
And it's been solved.
