### ISSUE TITLE
Can not upgrade to typescript@3.9 official version

### ISSUE THREAD

**Issue by snowyu** [isomorphic-git/isomorphic-git#1173]
```bash
git clone https://github.com/isomorphic-git/isomorphic-git
cd isomorphic-git
nvm use 10
npm i
# upgrade typescript to 3.9
npm i typescript@3.9 -D
npx nps build.rollup
# run the typescript compiler to create ts declaration files
node_modules/.bin/tsc -p declaration.tsconfig.json
# run the type test
npx nps test.typecheck
...
  index.d.ts:3390:5
    3390     dir: string;
             ~~~
    'dir' is declared here.


Found 542 errors.
```

**Comment by jcubic** [comment]
Sorry for the late reply but the project was in a suspended state, and I just become a new maintainer and I'm handling all issues, one by one.

Can you show exactly what error it is and how to reproduce?

**Comment by jcubic** [comment]
Thanks for updating but what errors you got, you only show what you do and don't show the actual errors. It would better if you just copy/paste everything inside details.
```
<details>
xxx
</details>
```

The reason why I need this is because I don't have any such errors after upgrading to TypeScript 3.9.

**Comment by snowyu** [comment]
ok here it is: [errors.txt](https://github.com/isomorphic-git/isomorphic-git/files/6744672/errors.txt). Maybe you should clone a fresh and clean git to test.

**Comment by jcubic** [comment]
Will check.

**Comment by jcubic** [comment]
Can I ask why you want to use the latest TypeScript, but obsolete Node version? And why you're modifying the library itself. I don't understand why you report this. Please explain.

**Comment by snowyu** [comment]
For I wanna port the lib to ts,  and then the cjs problem(node version) should be also solved naturally.
But the weird bug...

**Comment by jcubic** [comment]
If you want to port the library then you need to handle all issues yourself. This is not a bug in the library that you can't modify the project in the way you like.

It's more of a question and it's out of scope for this issue tracker, I suggest asking on StackOverflow with a typescript tag. I suspect that this has something to do with ES modules.

PS: I have no idea why you want to port to TS, the output will be the same (both will be compiled to JavaScript). Porting usually is done if you want to support a different platform. Here platform is the same. See Wikipedia article: [Porting](https://en.wikipedia.org/wiki/Porting). But of course, it's not my time will be wasted.

**Comment by snowyu** [comment]
Ok, fair enough.  how about the node js version to fix the v10?

**Comment by jcubic** [comment]
I'm trying to run the project locally and still have issues. But I'm using Node v12 that is more likely to work. The v10 support is for the library on npm that is compiled, not the Git repo itself. Build works fine in CI but I'm not able to run `npm test` locally.

I will want to update NodeJS to the latest version, or maybe just find the version that works. With a new version of Node build script filed because they were created before there was a breaking change of using ES Modules as default if package.json have `type: module` old version of Node didn't support ES Modules, so everything was working, after upgrade of Node everything is broken. Also the library that is used for build `nps` doesn't work with ES Modules.

**Comment by snowyu** [comment]
I can not run the `nps` locally on v12. So I have to swtch to v10.
For  `isomorphic-git` is an ES module and `package-scripts.js` is a common js.

**Comment by jcubic** [comment]
If you use v12.0.0 it works, only more recent v12 added ES support, and that breaks the nps that don't work with ES modules. The problem is `nps-utils` that don't allow to use nps config in different file (with cjs extension that fix ES Module with nps) I think that I will just need to remove nps, I don't see the benefit. There is an issue open in nps-utils since 2017, and that library is only a few lines of code. One more reason to keep dependency to the minimum.

**Comment by jcubic** [comment]
`npm run test` works in v12.0.0 but din't finish it fail on `webpack`.
