### ISSUE TITLE
Massive performance degradation since v1.7.5

### ISSUE THREAD

**Issue by stefan-guggisberg** [isomorphic-git/isomorphic-git#1251]
using node v12.18.3

Version 1.7.5 introduced a regression which causes a massive performance degradation. 

Test code:

```javascript
const fs = require('fs');

const git = require('isomorphic-git');

const dir = '.';
const filepath = 'README.md';
const ref = 'master';

const run = async (label) => {
  console.time(label); 
  
  console.time('resolveRef'); 
  const commitSha = await git.resolveRef({ fs, dir, ref });
  console.timeEnd('resolveRef'); 

  console.time('status'); 
  const status = await git.status({ fs, dir, filepath });
  console.timeEnd('status'); 

  console.time('readObject #1'); 
  const { oid } = await git.readObject({ fs, dir, oid: commitSha, filepath });
  console.timeEnd('readObject #1'); 

  console.time('readObject #2'); 
  const { object: content } = await git.readObject({ fs, dir, oid });
  console.timeEnd('readObject #2'); 

  console.timeEnd(label); 
}

const main = async () => {
  await run('total run #1');
  await run('total run #2');
}

main().catch(err => console.log(err));
```

I've tested with this repository: https://github.com/davidnuescheler/pages

**Results using 1.7.4:**

```
resolveRef: 2.276ms
status: 364.792ms
readObject #1: 2.695ms
readObject #2: 1.940ms
total run #1: 376.457ms

resolveRef: 0.672ms
status: 9.638ms
readObject #1: 2.091ms
readObject #2: 1.598ms
total run #2: 14.323ms
```

**Results using 1.7.5:**

```
resolveRef: 2.181ms
status: 359.206ms
readObject #1: 224.917ms
readObject #2: 228.641ms
total run #1: 819.938ms

resolveRef: 2.451ms
status: 247.968ms
readObject #1: 218.427ms
readObject #2: 229.541ms
total run #2: 698.930ms
```

=> The second run takes ~40-50x longer using 1.7.5.

related issue: #1237

**Comment by stefan-guggisberg** [comment]
@wmhilton Any chance you can have a look? We've reverted to 1.7.4 now.

**Comment by wmhilton** [comment]
👀 I'll take a look at it today

**Comment by wmhilton** [comment]
Ohh... well, that's kind of expected. The one that takes longer is `readObject` and that's because it has to reload and parse the packfile, because we no longer keep the parsed packfiles around indefinitely because that leaks memory (and quite a lot, quite quickly, depending on how isomorphic-git is being used). How are you using `readObject` in production? I've been meaning to figure out how to properly expose the internal caching mechanisms to library users, and this would be a good example.

**Comment by wmhilton** [comment]
The cache API I'm thinking of might look something like:

```js
const fs = require('fs');

const git = require('isomorphic-git');

const dir = '.';
const filepath = 'README.md';
const ref = 'master';

const run = async (label) => {
  const cache = {};
  console.time(label); 
  
  console.time('resolveRef'); 
  const commitSha = await git.resolveRef({ fs, dir, ref, cache });
  console.timeEnd('resolveRef'); 

  console.time('status'); 
  const status = await git.status({ fs, dir, filepath, cache });
  console.timeEnd('status'); 

  console.time('readObject #1'); 
  const { oid } = await git.readObject({ fs, dir, oid: commitSha, filepath, cache });
  console.timeEnd('readObject #1'); 

  console.time('readObject #2'); 
  const { object: content } = await git.readObject({ fs, dir, oid, cache });
  console.timeEnd('readObject #2'); 

  console.timeEnd(label); 
}

const main = async () => {
  await run('total run #1');
  await run('total run #2');
}

main().catch(err => console.log(err));
```

This is in fact what's used internally... I just haven't exposed it yet because explaining it is a little weird and I keep wondering if there is a better way, like transactions.

AFAICT I have to decide whether the default behavior is performant (keeps caches around) or free of memory leaks (frees caches after commands run). There might be a middle ground (LRU cache?) but that ends up compromising both performance and memory in some cases, so it's probably better to expose it so users can decide.

Another option is to keep caches around and then have a new function like `git.clearCache({ dir })`. But I kind of hate to have a library that leaks memory by default unless you remember to manually clear the caches.

**Comment by wmhilton** [comment]
Eh, it's kinda hard to tell if it's working because on my repo (isomorphic-git) it runs pretty fast regardless... I would need a bigger repo to see the orders of magnitude slowdown/speedup you're seeing... but here's what I'm seeing if I [expose the `cache` parameter](https://github.com/isomorphic-git/isomorphic-git/pull/1255/files):

```
|          main            |       feat/cache-api      |
|--------------------------|---------------------------|
|  > node test.js          |  > node test.js           |
|  resolveRef: 5.676ms     |  resolveRef: 4.797ms      |
|  status: 42.204ms        |  status: 42.457ms         |
|  readObject #1: 12.298ms |  readObject #1: 13.528ms  |
|  readObject #2: 6.004ms  |  readObject #2: 5.876ms   |
|  total run #1: 68.269ms  |  total run #1: 68.680ms   |
|                          |                           |
|  resolveRef: 1.426ms     |  resolveRef: 1.439ms      |
|  status: 20.236ms        |  status: 9.421ms          |
|  readObject #1: 2.761ms  |  readObject #1: 3.386ms   |
|  readObject #2: 3.176ms  |  readObject #2: 2.527ms   |
|  total run #2: 27.869ms  |  total run #2: 16.992ms   |
|                          |                           |
|  resolveRef: 1.367ms     |  resolveRef: 1.220ms      |
|  status: 13.004ms        |  status: 5.051ms          |
|  readObject #1: 2.653ms  |  readObject #1: 2.301ms   |
|  readObject #2: 1.930ms  |  readObject #2: 1.472ms   |
|  total run #3: 19.180ms  |  total run #3: 10.264ms   |
|                          |                           |
|  resolveRef: 0.951ms     |  resolveRef: 0.873ms      |
|  status: 10.280ms        |  status: 4.228ms          |
|  readObject #1: 9.374ms  |  readObject #1: 13.383ms  |
|  readObject #2: 1.356ms  |  readObject #2: 2.022ms   |
|  total run #4: 22.152ms  |  total run #4: 20.773ms   |
|                          |                           |
|  resolveRef: 0.938ms     |  resolveRef: 2.148ms      |
|  status: 9.371ms         |  status: 4.455ms          |
|  readObject #1: 2.886ms  |  readObject #1: 2.555ms   |
|  readObject #2: 1.736ms  |  readObject #2: 1.795ms   |
|  total run #5: 15.153ms  |  total run #5: 11.224ms   |                
```

**Comment by stefan-guggisberg** [comment]
Thanks @wmhilton for looking into this. 

> Is this the actual sequence of commands used in production?

The actual sequence (and other sequences) is used by https://github.com/adobe/git-server, our GitHub Protocol & API emulation that we're using in our local development tooling. 

The local development tooling serves dynamic websites via our local GitHub emulation. The performance hit that we're seeing is most notable with larger repositories, e.g. https://github.com/davidnuescheler/pages. This has become painfully slow, to the point of being unusable.

**Comment by stefan-guggisberg** [comment]
> I would need a bigger repo to see the orders of magnitude slowdown/speedup you're seeing.

Thanks for sharing this. Could you run the test code with a local clone of this repository?  https://github.com/davidnuescheler/pages.

**Comment by stefan-guggisberg** [comment]
I went ahead and tested with before mentioned repo:

**v1.7.8:** 

```
resolveRef: 2.230ms
status: 400.173ms
readObject #1: 294.029ms
readObject #2: 278.865ms
total run #1: 981.091ms

resolveRef: 1.959ms
status: 231.133ms
readObject #1: 254.164ms
readObject #2: 254.196ms
total run #2: 742.023ms

resolveRef: 2.117ms
status: 230.299ms
readObject #1: 229.716ms
readObject #2: 275.966ms
total run #3: 738.623ms

resolveRef: 2.010ms
status: 231.274ms
readObject #1: 228.124ms
readObject #2: 239.396ms
total run #4: 701.301ms

resolveRef: 1.771ms
status: 241.533ms
readObject #1: 223.004ms
readObject #2: 236.289ms
total run #5: 703.025ms
```

**exposed cache param:**

```
resolveRef: 2.162ms
status: 352.665ms
readObject #1: 2.634ms
readObject #2: 1.923ms
total run #1: 364.962ms

resolveRef: 0.599ms
status: 2.456ms
readObject #1: 2.215ms
readObject #2: 1.469ms
total run #2: 7.018ms

resolveRef: 0.456ms
status: 1.888ms
readObject #1: 1.503ms
readObject #2: 0.670ms
total run #3: 4.739ms

resolveRef: 0.443ms
status: 2.021ms
readObject #1: 1.281ms
readObject #2: 0.485ms
total run #4: 4.443ms

resolveRef: 0.454ms
status: 1.675ms
readObject #1: 1.213ms
readObject #2: 4.168ms
total run #5: 7.717ms
``` 

It's roughly a 100x improvement.

**Comment by wmhilton** [comment]
Gah... 100x?! Problem is now I want that to be the default. I've got a freaking 3-legged stool: fast, low-memory, and easy-to-use-well.

A LRU packfile cache of size of 1 that persists between commands would probably work really well for 99% of cases... but is that gonna be worse for the 1% of cases and just make it harder...

I'll make some decision by the end of the week and get a "fix" out this weekend. Whether that's a "fixed by default" or "fixed if you change your code to opt in" I dunno yet.

**Comment by stefan-guggisberg** [comment]
Thanks @wmhilton, really appreciated!

**Comment by stefan-guggisberg** [comment]
Thank you very much, @wmhilton. That solved our performance issue.
