### ISSUE TITLE
Expose commit signing payload

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#131]
We can eliminate the awkward dependency injection of OpenPGP.js and make the API truly agnostic (which I need if I want to try using kbpgp) by the following:

instead of `verify`, add an option to `commit` and `log` to expose the output of GitCommit.withoutSignature() as `payload` and GitCommit.isolateSignature() as `signature`.

instead of `sign`, expose GitCommit.fromPayloadSignature({payload, signature})

thus instead of:
```js
await git.commit(...)
await git.sign(...)
```

one would do:
```js
let {payload} = await git.commit({..., signing: true});
let signature = YourLibraryPGP.sign(payload);
await git.replace({signature, payload});
```

**Comment by getify** [comment]
Here's an alternate suggestion, which comes from a similar topic in the node-git library.

Allow defining a callback called `onSignature` (or whatever) instead of `signing: true`... if specified, this callback is invoked with the payload of the commit, and should return a promise -- so it's likely best if it's an `async function` given for the callback -- which resolves to the signature for the payload.

This idea of a callback fits nicely in what node-git already does, which is that they also have callbacks for other kinds of things, like providing authentication details, etc. But I think it would also be more ergonomic for your users -- fewer steps, less to mess up -- but still provide the loose dependency on a PGP library that you're hoping to get.

**Comment by wmhilton** [comment]
Yes, I started down a similar-ish path in #137. I think I'll end up exposing a hook that users can use. It's less awkward than the solution I proposed above, and rather than having to pass a callback parameter, a the plugin system would let you configure it once and be done.

Since this issue describes an earlier idea, before the plugin system, that I probably won't implement, I will go ahead and close this issue.
