### ISSUE TITLE
Git 2.28 introduces init.DefaultBranch

### ISSUE THREAD

**Issue by nelsonni** [isomorphic-git/isomorphic-git#1328]
According to the [announcement of the Git 2.28.0](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) release:

> When you initialize a new Git repository from scratch with `git init`, Git has always created an initial first branch with the name `master`. In Git 2.28, a new configuration option, `init.defaultBranch` is being introduced to replace the hard-coded term. (For more background on this change, [this statement from the Software Freedom Conservancy](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) is an excellent place to look).
>
> Starting in Git 2.28, `git init` will instead look to the value of `init.defaultBranch` when creating the first branch in a new repository. If that value is unset, `init.defaultBranch` defaults to `master`. 

Therefore, we should update the `defaultBranch` value within isomorphic-git to conform to this new canonical behavior. 

https://github.com/isomorphic-git/isomorphic-git/blob/f2e38053733f4c8ca4b7784d5c2a56addcf36bf4/src/api/init.js#L25-L31

We probably could use [`getConfig`](https://isomorphic-git.org/docs/en/getConfig) to check for whether `init.defaultBranch` has been set, and default back to `master` if it isn't. However, that brings up a problem since the Git documentation recommends that users set `init.defaultBranch` in the global scope (i.e. `git config --global init.defaultBranch main`), and [`getConfig`](https://isomorphic-git.org/docs/en/getConfig) can only check the local `$GIT_DIR/config` file.

**Comment by jcubic** [comment]
Please explain because I don't understand you have the option `defaultBranch` to init API function, which is set to master if not set.
Which is exactly what canonical git does. So what you expect to happen? Reading global git config? There is no global git config in the browser. Sorry I need to close this issue.

**Comment by nelsonni** [comment]
My expectation is that isomorphic-git can at least read the `init.defaultBranch` setting at the project scope, which does exist in the browser, and default to `master` if no such option is set.

My understanding was that isomorphic-git was supposed to target both browsers **and** Node apps. My own project uses isomorphic-git within an Electron app, so I am able to assume the existence of a global `git-config`, which I handle separately by wrapping `getConfig` and similar commands with additional code to handle. I don't expect isomorphic-git to support that use case, but I do know that previous attempts to adhere to the standard git behavior have been important in the project and this was an attempt to have a conversation about the best way to deal with this particular difference in behavior.

(Side note: If you ask clarification questions and then immediately close the issue, how should I interpret that? Why should I respond in an issue that is clearly not welcomed?)

**Comment by jcubic** [comment]
Sorry, but when you init the project there is no git repo yet, how do you want to read the project scope then?

If you have an electron app you can easily search for the global config file read the `init.DefaultBranch` property and pass it to `git.init`. Isomorphic-git doesn't handle global git config file and I don't think it will because of the browser where this will be troublesome, it's easier to just use parameter.
