### ISSUE TITLE
Improve recursive rm

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#1383]
This is a continuation of the discussion in #1283.

The idea is to use fs.rm if it's present that allow for recursive delete, the docs will be updated, so it will be required to implement in new code. fs.rm is also available in the newest Node.

**Comment by mojavelinux** [comment]
I want to take this point a little further. I'd like to see the logic of recursively deleting a directory encapsulated by the `rm` function on the FileSystem object that isomorphic-git uses rather than exposed as an external helper. The FileSystem object can detect the availability of `rm` on the built-in `fs` object and use it if present (starting with Node 14). Otherwise, it would provide the implementation currently being used.

The main motivation for doing this is that removing a directory recursively on Windows is prune to race conditions, and we don't want to have to deal with those conditions in isomorphic-git. Instead, Node.js takes on this burden for us (and it really has to work hard, as you can see by the [docs for rm](https://nodejs.org/api/fs.html#fs_fs_rm_path_options_callback)).

I don't think this has to impact users of the library since we would be providing a fallback implementation. However, it is certainly still prudent to document it.

**Comment by jcubic** [comment]
I'm wondering how much we need to support Node <14. Node is usually something that is controlled by the developer, not like the browser. Maybe we just implement fs.rm in lightingFS and use nodeJS `fs.rm` and update NodeJS requirement.

**Comment by strangedev** [comment]
I think we should leverage the more modern node API. Node 12 is EOL in April 2022 anyway, so people will need to start phasing it out soon.

**Comment by mojavelinux** [comment]
Requiring Node 14 would be very harsh, especially in my case. While it's true that the Node project itself puts versions into EOL, that doesn't mean distributors don't still support it (think a Linux distribution, for example). And since this is such a specialized feature, I think bumping the requirement for Node.js would be way too drastic. We can gracefully handle different capabilities of fs providers without going to that measure.

**Comment by mojavelinux** [comment]
Forcing an upgrade of a platform to use a library is something that should be done with extreme care and consideration. It can result in an application developer having to do an upgrade long before they are prepared, rushing it, making mistakes. I could concede for bumping the engine to Node 12 (with some reluctance, but it way too early for requiring Node 14).

**Comment by mojavelinux** [comment]
>  especially in my case

I want to illuminate what my case is. In my experience, the performance of Node.js > 10 is not nearly as good as Node.js 10. There were significant changes the memory model that impacted libraries that did a lot of string processing, like this one. It may end up just being something we have to accept, but for now several of my users are holding on to Node.js 10 for performance reasons. More analysis may be needed to understand how this impacts isomorphic-git specifically.

**Comment by mojavelinux** [comment]
If it's a matter of who has the time, I'm willing to implement this feature. All I want to do is pull the logic into the FileSystem object and use what we have available to us, using fallback code where necessary. It's quite a simple change.

**Comment by mojavelinux** [comment]
This turned out to be pretty straightforward to implement. I didn't want to introduce a new method to the FileSystem model, so instead I updated `rmdir` to recognize the recursive option. If the option is set, then we delegate to `_rm` to delete the directory recursively. If the recursive option is not set (or there are no options), it works as before. So no one using this API should be affected. If the fs provider does not implement `rm`, we plug in our fallback (which I revised to be simpler).
