### ISSUE TITLE
The initial default branch is not defined correctly if branches do not exist.

### ISSUE THREAD

**Issue by radzserg** [isomorphic-git/isomorphic-git#1421]
If I initiate a new git repository with a custom initial branch 

```sh
git init -b v2
```

when I try to clone it, new git repo will be [`init_`-iated](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/commands/init.js#L20) with hardcoded `master` branch. Then `fetch` [returns null](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/commands/fetch.js#L129) as a defaultBranch and HEAD won't be updated to `v2`. 
As a result _currentBranch will return `master`

### Expected behavior:

If git is initiated with non-master branch - _currentBranch should return correct branch name after cloning.

**Comment by jcubic** [comment]
Can you explain how you go from `git init` to `git clone`? Can you show the steps you're using?

**Comment by jcubic** [comment]
`git init` is local, `git clone` is remote? You need to have push somewhere that you didn't included in your issue.

**Comment by radzserg** [comment]
My expectations were as follows. When I create a new repository on Github it initialized it with the default `main` branch. So when I clone it I should have `ref: refs/heads/master` inside the `.git/HEAD`. 
But you're right. I have to push something otherwise it doesn't make sense. 
Moreover, when we clone an empty repository from Github it still has `ref: refs/heads/master` in `.git/HEAD`. 
Closing this one.

**Comment by jcubic** [comment]
But you pushed something to remote? I don't understand. You only mention that you init and clone, where the push?

**Comment by jcubic** [comment]
You can't clone an empty repo. I would say that the result is unspecified behavior, but you can look into canonical git and see what will happen.

**Comment by wmhilton** [comment]
Ah yeah. @radzserg you're trying to fix the bug where if you create a new empty repo on GitHub but in your GitHub personal preferences have configured the default branch for new repos to be "main" instead of "master", and you do a git clone, you're not checked out on the right branch, aren't you? Yeah. Cool expectations, but as you've noticed, canonical git fails that test as well. :-( Cloning an empty repo puts you in a detached HEAD state and HEAD ends up pointing at whatever your _local_ settings (configured via `init.defaultBranch` in your `~/.gitconfig`) for new repos are.

In fact, even the GitHub instructions for cloning are different and manually include `-b main` in the instructions:
![image](https://user-images.githubusercontent.com/587740/132361874-a9b68f19-3e7f-4aa2-956d-e260826d006c.png)

As far as I can tell, there is no way with the common git protocol to ask a remote "I know there's no branches, but _if there were_ what would be the default branch?" So if we want to implement that in Stoplight, I think we'd need to use the GitHub API to ask what the default branch name should be.
