### ISSUE TITLE
Significant Memory leak when calling getRemoteInfo() 

### ISSUE THREAD

**Issue by PhilDay-CT** [isomorphic-git/isomorphic-git#1583]
Using node  v16.4.0

Using isomorphic-git in out project to monitor a repo in github we got a memory leak which eventually killed our process.    Tracking it done we think it comes from each call to getRemoteInfo()  - which we use to decide whether to do a pull or not. 

The attached example reproduces the issue - it needs to be modified to use a valid set of github credentials and a PAT token. 
 
[example.tar.gz](https://github.com/isomorphic-git/isomorphic-git/files/8757036/example.tar.gz)

When run it makes a call to getRemoteInfo() every 5 seconds and prints the heapsize before and after.  The heap seems to grow by about 30-40KB on each call.

Using chrome://inspect on the running example shows (amongst other items) TLSSocket and TLSWrapo objects being created and having a retained size - suggesting that perhaps something is not being properly closed / released after each call ?
![Selection_115](https://user-images.githubusercontent.com/69908274/169878838-8c787270-b5d4-4b62-b755-a80b1146b572.png)

```
$ node  --expose-gc  agent.js
Doing Pull
Pull done Heap Increased by 336416
Doing Pull
Pull done Heap Increased by 51952
Doing Pull
Pull done Heap Increased by 39224
Doing Pull
Pull done Heap Increased by 41448
Doing Pull
Pull done Heap Increased by 44504
Doing Pull
Pull done Heap Increased by 38120
Doing Pull
Pull done Heap Increased by 29616
Doing Pull
Pull done Heap Increased by 34016
Doing Pull
Pull done Heap Increased by 38056
Doing Pull
Pull done Heap Increased by 32552

```

**Comment by jcubic** [comment]
Hi, thanks for the report. But I'm afraid if you don't fix the issue and contribute no one will do that for you. This project was created by @wmhilton that is not active anymore. I'm an active maintainer, I've taken the project so it does not die. But I'm not coding myself much. 

Note that we have some money on OpenCollective, I don't know yet how to get them out, but we can pay for fixing this issue. Since this looks like an important bug that needs to be fixed. But I don't know anyone that would like to fix it. If you don't want to code yourself, maybe you can find someone that will code for you.

**Comment by PhilDay-CT** [comment]
OK, thanks for the feedback.

I'll do some more digging and see if I can work out what's going on, but TBH unless I can find an obvious fix (and I have a horrible feeling its going to be down in the weeds somewhere) I'll probably have to change direction and call git directly via exec.

Is there some way to get the current support status a bit more prominent in the ReadMe and/or npm - so folks get a better idea of what they're getting into ?

**Comment by PhilDay-CT** [comment]
Further investigation seems to point to some interaction between our system and the underlying simple-get module, so closing this issue.
