### ISSUE TITLE
Invalid checksum in GitIndex buffer

### ISSUE THREAD

**Issue by booknownick** [isomorphic-git/isomorphic-git#1626]
Using Salesforce CLI Integration to push metadata to a scratch org.

Starting SFDX: Push Source to Default Scratch Org

10:42:41.247 sfdx force:source:push --json --loglevel fatal
10:42:43.136 sfdx force:source:push --json --loglevel fatal
 ended with exit code 1

Internal: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 61756c742f6f626a656374732f4c6f675f5f632f but saw 83ca14c99d516cf6cf22915d316c637a84aa4858

**Comment by jcubic** [comment]
Sorry, but we will not be able to help you. This project is driven only by volunteers. I'm the maintainer but I don't code myself much. If you would like this to be fixed you will need to debug the code yourself, since no one will be able to help with your problem. Especially that's a technology that I'm not familiar with.

**Comment by booknownick** [comment]
Appreciate it.
