### ISSUE TITLE
sfdx push error - Index file is empty (.git/index)

### ISSUE THREAD

**Issue by aldensc** [isomorphic-git/isomorphic-git#1776]
Using VS Code
sfdx force:source:push -f canceled, as it was hanging for minutes.
Second try results in this error.

Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

Tried using "sf project deploy start", but this error occurs...

Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709

Second day in a row that this has occurred.  I had to create a new scratch org to get around the issue the first time.  Is there a way to fix my org?  I am reporting the error as the error message requests.  I have killed hung pushes in the past many times and never ran into this issue.

**Comment by jcubic** [comment]
Reported in #1774, #1733. If you report the issue to any Open Source project please search if similar issue does not exist already.

**Comment by jcubic** [comment]
Someone in #1768 suggested that the issue is because of the status matrix that was hanging, it was that bug that we reverted, the first time the CI/CD didn't run but the License change I made forced the release. So I think that only update of the library is needed.


BTW: @dead-end you're really helpful by answering issues, do you want to join the org and be part of the team? It will be really helpful if someone keep answering issues, even if this is all that the person will do. But if you will want to contribute with code, you will be able to create a PR on this repo, not need for a fork. You can also join [Gitter Chat](https://app.gitter.im/#/room/#isomorphic-git_Lobby:gitter.im).

I will only need to see check how to invite you. What do you say?

**Comment by dead-end** [comment]
@jcubic: First of all, thank you for inviting we to the team. To be honest, I am a Java developer and at my work we are still using svn. My knowledge about git, javascript, typescript and node is limited. I like writing software and I want to contribute some, but my limited knowledge is an issue.

I will continue to support the team, but for now I think my status is sufficient.

**Comment by dead-end** [comment]
The issue at foresales: [https://github.com/forcedotcom/cli/issues/2194](https://github.com/forcedotcom/cli/issues/2194)

**Comment by jcubic** [comment]
IF that closed issue doesn't help Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues) as a separated issue.

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.
