### ISSUE TITLE
Index file is empty (.git/index) forcedotcom/cli#2194

### ISSUE THREAD

**Issue by otiliaveresRV** [isomorphic-git/isomorphic-git#1785]
When I use the command in VsCode: 

$ sfdx force:source:status
Warning: We plan to deprecate this command in the future. Try using the "project retrieve/deploy preview" command instead.
Error (1): An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

**Comment by thvd** [comment]
@otiliaveresRV Please refer to this https://github.com/forcedotcom/cli/issues/2194

**Comment by dead-end** [comment]
@otiliaveresRV Did you killed the push, because it was running too long before you got the error?
The error message says that the git index file is empty, but this does not seam to be the `.git/index` file as mentioned in the error message above. Do you have one of the file (after replacing the orgId) and if so is it empty?
```
.sfdx/orgs/[orgId]/localSourceTracking/index
```
or
```
.sf/orgs/[orgId]/localSourceTracking/index
```

**Comment by otiliaveresRV** [comment]
@dead-end There is that possibility
And now the folder .sfdx/orgs/[orgId] is Empty

I work with sandbox and I can't delete the org.
What I can do?

**Comment by dead-end** [comment]
@otiliaveresRV Sorry, but I do not know much about salesforce. If you need more infos, see: https://github.com/forcedotcom/cli/issues/2194
