### ISSUE TITLE
question comparing this library to node-git, for modifications to a git repo

### ISSUE THREAD

**Issue by getify** [isomorphic-git/isomorphic-git#179]
Forgive me if I've missed this detail in the docs, but... is there a way to modify a git tree (repo) in any way without using the file system to do so?

In node-git, they have the concept of working directly with the tree, creating/deleting/renaming nodes (files, directories, etc), so you don't have the mess of dealing with file system operations. They accomplish this by using the libgit2 bindings directly. In fact, their API is almost a 1-to-1 exposing of that API in JS.

Is there any equivalent of something like that here? Is there any intention to ever have that?

**Comment by wmhilton** [comment]
Your question is a little complicated, because git repos are generally stored on a file system - why I ultimately built isomorphic-git on the prerequisite of a file system library: 'fs' in Node, or 'BrowserFS' in browsers. That said, there's a couple ways to interpret your question, so I'll try to just answer in every way I can think of.

**Is it possible to create git objects (blobs, trees, commits, etc) purely in memory without saving them to disk?** Yes and no. Internally, the [src/models/](https://github.com/isomorphic-git/isomorphic-git/tree/424e5be5bbca33062650c9bfb180a0d158e48c2a/src/models) folder has individual classes for creating things like raw Objects, Trees, Commits, Packfiles, Pack Index files and serializing them to Buffers. However, none of those classes are directly exposed by `isomorphic-git`, because they're not API stable (yet) so you'd have to use the source code from Github rather than the npm package.

**Is it possible to manipulate a git repo without using a working directory?** There is a [`readObject`](https://isomorphic-git.github.io/docs/readObject.html) function that I added based on feedback from another node-git user. Mostly I imagined it being used to efficiently crawl/search git repos without having to do an actual checkout. But it's pretty general purposely powerful. For some reason I haven't added a `writeObject` function to go along with it, but I could do that if I were asked.

OK I thought there were more ways to interpret the question but I can only think of the two right now. Hopefully one of those answers were helpful!

**Comment by getify** [comment]
Yeah the use-case for me is working with a bare repository which has no working directory, so obviously the file system approach doesn't work.

**Comment by getify** [comment]
> Again, that boils down to whether you really mean "no filesystems" as in you need an in-memory solution that doesn't touch the disk

I don't mean that, I just mean that with a bare-repository, the normal directory/file structure of the repository is not reflected in a location where I can add/remove/rename files using normal filesystem operations. Like, if all I have is a bare repository, I couldn't go the command line and type `ls -l` and see all the files in some directory inside it.

I know the bare repository is storing some kind of representation of the current state of the repo, and that's on disk, and ostensibly its in some kinds of files and directories. But I'm not at all familiar with the internals of how git stores these artifacts in its bare-repository representation on disk, so I wouldn't have the faintest clue about how to add/remove/rename files or subdirectories by using filesystem commands to modify those artifacts.

So, here's a use-case that would be typical for me to need to do against a bare repository:

1. Look inside a sub-directory of the repo
2. Find a specific file by name
3. Read its contents
4. Update its contents

Here's another use-case that would be equally typical:

1. Find a specific file by name inside a sub-directory, read its contents
2. Create a new sub-sub-directory inside the sub-directory
3. Inside the sub-sub-directory, make a new file that's got modified contents from the original file
4. Delete the original file

All of those things would be trivial with normal filesystem commands (think things I could do from the command line) if I had a normal full repository. But with a bare repository, I can't really imagine how, using filesystem commands, I alter the state of this bare repository in those ways.

By contrast, the node-git library provides this TreeWalker abstraction that, at least from its ergonomics, feels like this "virtual representation" of the repository's tree, which you can traverse up and down, add to and remove and rename, and then when you're done, sorta commit that new "tree" back as the new repository state.

That's what I mean by manipulating the repository without filesystem commands.

**Comment by creationix** [comment]
Right, so `normal-repo/.git/` has the same structure as `bare-repo.git`.  It's a git database (key-value where key is literally sha1 of value) containing git objects.  There are commit objects, tree objects and blob objects. all linked together using hash pointers.  You can read any file in a git database by walking the graph.  A nice abstraction for people coming from path-based FS interactions would be something that takes commit hash + file path and gives you the hash of the blob or tree at that location.  I had this somewhere in js-git and used it heavily in the tedit editor.

Writing changes back is a little more complicated.  You need to create a new blob entry with a new hash for the modified file contents and save that to the database.  Then for each parent tree of the file, you need to create a new tree with the hash for the file updated to reflect the updated contents.  Recurse this up to the root tree creating new objects as you go.  Then create a new commit object that points to this new root tree and the parent commit(s) and save this to the database.  Once you have the new commit, and trees/blobs, the ref for your branch needs to be moved to point to the new commit hast and the changes are now saved.

I also had abstractions for this kind of path based write operation, but it's a lot more complicated and there is some assumptions here about the nature of the commit metadata and which branch to move.

Something I did in tedit was use a temporary ref where each FS edit resulted with a new root tree and new commit, but the commit was always squashed and pointing directly to the last real commit in HEAD.  When my users wanted to do a real commit with message, I would simply take that root tree from my temporary ref and create a real commit and move HEAD's ref.

Tedit always used bare repos, there was no working directory.

**Comment by wmhilton** [comment]
@getify Your use case sounds really similar to the stuff @mojavelinux was working on. The short answer is: yes, you _can_ do all those things you mention, it's just a little tedious and awkward.

In some issue I was ruminating on the need for a `writeObject` to accompany the `readObject` command. Maybe that's what I'll do next. That, and add a `filepath` parameter to `readObject` so you can navigate straight from a `tree-ish` to a `blob` or `tree` without the intermediate step of doing `readObject` for every tree along the way.

**Comment by mojavelinux** [comment]
I can confirm that it's possible to read the git repository without ever having a worktree. In Antora, I work almost exclusively with bare repositories and I can confirm the the filesystem is only touched for the purpose of reading the refs, index, and pack files (the same thing libgit2 does).

I would also like to be able to write to the bare git repository without a worktree. That part doesn't seem possible yet without the `writeObject` function @wmhilton proposed.
