### ISSUE TITLE
Internal: An internal error caused this command to fail. error message: Invalid checksum in GitIndex buffer: expected 6574732f69636f6e732f616374696f6e2f636c6f but saw a8d41bc3b39866e3614b2c285d5df00273b255d0

### ISSUE THREAD

**Issue by Marily20** [isomorphic-git/isomorphic-git#1802]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

**Comment by jcubic** [comment]
Can you provide information on what kind of tool you're using? Do you use VS Code with Salesforce maybe? If don't provide any information this will be closed and ignored.

**Comment by mohit18111995** [comment]
I am also facing the same issue from today "An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 00000000000000b3a75683e278d84f0f3efba00c but saw 15d134c618207173182beadf75b1f099af4e77e7"

The issue comes when I try to run "sfdx force:source:push -f" command from VS Code to Salesforce.

**Comment by jcubic** [comment]
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues)
