### ISSUE TITLE
How to clone to directory and then list files from it in browser

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#188]
I've tried to clone repo and then list the files. it works fine if I use '.' as dir option but when I've tried to use different directory so I can have more then one repo it don't work:

The other issue is that when I clone to dir I can't clone again to '.' I need to delete the database.

Here is my playground https://codepen.io/jcubic/pen/Gddxpg?editors=0010 (I wanted to recreate whole git cli using jquery terminal and then maybe add editors like ymacs and jsvi) but stumble upon a roadblock when I've just started.

If you type:
```bash
git clone https://github.com/isomorphic-git/isomorphic-git .
ls .
```
you will get list of files but this will not work:

```bash
git clone https://github.com/isomorphic-git/isomorphic-git git
ls git
```

**Comment by jcubic** [comment]
Ok, the gitdir is for this.

**Comment by wmhilton** [comment]
What a cool idea! I've wondered about that, whether someone could write a parser that converts git's string-based command line arguments into isomorphic-git JSON-based arguments. I suggest using codesandbox.io though rather than CodePen though just because codesandbox has a much nicer editor. Happy coding!
