### ISSUE TITLE
Most efficient way to fetch a single file from a given revision or branch?

### ISSUE THREAD

**Issue by njlr** [isomorphic-git/isomorphic-git#230]
Suppose I have a Git URL + revision and I want to fetch the `README.md` file, if present. 

My current solution is to: 

- Create a temporary folder
- Git clone from the URL into the folder
- Git checkout the revision, branch or tag
- Read
- Clean-up the folder

This works, but is it the best approach using isomorphic-git? 

I believe that the `git` CLI tool can do this efficiently using `git archive`.

**Comment by wmhilton** [comment]
Honestly the most efficient solution would probably be to use the Github/Bitbucket/Gitlab API. But

**Comment by wmhilton** [comment]
I should add an option to checkout to check out a specific filepath. That would save a lot of disk thrashing.

**Comment by wmhilton** [comment]
OK you can now do this without calling `checkout` by calling [readObject](https://isomorphic-git.github.io/docs/readObject.html) with a `filepath` parameter:

- Create a temporary folder
- Git clone from the URL into the folder
- `let oid = await git.resolveRef({fs, gitdir, ref})` where `ref` is the revision, branch or tag
- `let {object} = await git.readObject({fs, gitdir, oid, filepath: 'README.md', encoding: 'utf8'})`
- Clean-up the folder

**Comment by wmhilton** [comment]
Adding `filepath` argument to `checkout` will happen too soon. But `readObject` is kinda nice for this case because you can get the README data directly as a string without writing it to disk.

Cloning is still slowed down by the fact it checks out the branch at the end, which involves writing all those files. You can get around that by using `init`, `config`, and `fetch` directly, instead of `clone`... but I bet there's enough common use case for "I want to clone a repo but all I care about is one file" that it might make sense to add an option to skip the `checkout` step at the end of a normal clone.

**Comment by wmhilton** [comment]
> it might make sense to add an option to skip the checkout step at the end of a normal clone.

FYI I have added a `noCheckout` parameter to `clone` in #240.
