### ISSUE TITLE
Is git fetch support 'ssh' protocol?

### ISSUE THREAD

**Issue by howardgod** [isomorphic-git/isomorphic-git#231]
Hi,

As I'm using 'git fetch', it fail to go with 'ssh' protocol?
Is 'ssh protocol' supported by isomorphic-git?
If it's not, will it be in the future?

thank you,

Howard

**Comment by wmhilton** [comment]
> Is 'ssh protocol' supported by isomorphic-git?

Not at the moment, no.

> If it's not, will it be in the future?

The SSH protocol will never work in the browser, unless the browser gets an API for creating raw TCP connections on port 22, so I won't be including SSH support in the `isomorphic-git` core. But creating raw TCP connections *is* possible in Node and Electron, and it will be easy (I think) to implement the `git+ssh` protocol as a `remoteHelper` plugin once I finish the [plugin API](https://github.com/isomorphic-git/isomorphic-git/issues/218).

**Comment by howardgod** [comment]
My bad,

I was saying about Node only. 

thanks

**Comment by keithslater** [comment]
Has there been any progress in bringing ssh to this project with the remoteHelper plugin?

**Comment by jods4** [comment]
Shouldn't this be kept open?

Isomorphic-git is a great library on node because of its lack of native dependencies (either git CLI or libgit2).

But when automating tasks on a server, it's common to use SSH keys instead of credentials. Lack of SSH support is sadly a deal breaker for several of my tasks.

As SSH isn't gonna be isomorphic soon, I would be perfectly fine with a remoteHelper plugin that works only in Node.
It looks like the removeHelper plugin model hasn't been finalized since this issue was opened.

**Comment by kwenyao** [comment]
Any progress or updates on the support for SSH? It is the only thing keeping me from moving my projects to isomorphic-git.

**Comment by Awpatterson217** [comment]
^ Same

**Comment by joaofrca** [comment]
^ same here!

**Comment by michael-kry** [comment]
^ Same

**Comment by bombillazo** [comment]
This feature would be ideal for node projects, not sure how to proceed with this library if I can't use ssh based git connections.

**Comment by jcubic** [comment]
@bombillazo do you want to contribute with support for this feature? I'm afraid that no one will do this work for you if you need this. This project doesn't have main author that would wrote the code. He left the project. I'm maintainer but I don't write code myself. Last time I did a bit of work on lightningFS.

**Comment by GamerGirlandCo** [comment]
> @bombillazo do you want to contribute with support for this feature? I'm afraid that no one will do this work for you if you need this. This project doesn't have main author that would wrote the code. He left the project. I'm maintainer but I don't write code myself. Last time I did a bit of work on lightningFS.

fine, i'll bite. where's the relevant code?

**Comment by jcubic** [comment]
But note that it may be difficult to support ssh protocol for the browser, you will need to write special kind of HTTP to SSH proxy.

**Comment by jcubic** [comment]
> fine, i'll bite. where's the relevant code?

You will need to read the code and find it for yourself. Sorry I don't have time to read the code for you.

**Comment by mojavelinux** [comment]
My $0.02. I think it would be best to focus on how to do it (as a plugin) without worrying about the browser at first just to understand the mechanics. Once that's working, then we could start to worry about what's possible in the browser.

**Comment by jcubic** [comment]
Sure but I would not merge if it works only on NodeJS. We can have some work branch where we will merge the PR.

**Comment by evictor** [comment]
What’s the update on this? I would and could happily contribute code.

**Comment by jcubic** [comment]
@evictor This will need to be implemented outside of the isomorphic-git library because SSH will not work in the browser.

But if you want to play with the code go ahead. It may help others. But note that it needs to be something that will be pluggable into the library. And plugins from version 0.x were removed in version 1.0.

**Comment by jmgurney** [comment]
Question, would supporting ssh over websockets be a viable option?  I've implemented this for another project and the gateway was easy to implement, it would require the server or a custom server to be a gateway though.

https://www.funkthat.com/gitea/jmg/wsfwd

**Comment by jcubic** [comment]
Didn't know something like this was possible. Does it require a proxy on the server or is it a Browser code that talks directly with SSH?

**Comment by GamerGirlandCo** [comment]
this _might_ be helpful — https://github.com/agladshteyn/BrowserSocket

only caveat is that it requires a node "relay" server to already be running somewhere else. do you think it'd still be worth trying though, despite that?

**Comment by jcubic** [comment]
You can try it as your own project, having a proxy server to allow SSH is out of scope for this project. You can't normally use SSH in the browser.

**Comment by Calisto-Mathias** [comment]
Heyyy! I just came across isomorphic-git as it is also being used by obsidian-git. Has any work been done on this particular issue. I would love to work on it in my free time if it hasn't already been implemented. 

It would help if you could point me to some resources or starting points? 

Thanks ;)

**Comment by jcubic** [comment]
@Calisto-Mathias I don't think that anyone worked on this. If you can work on this it would be great, but note that it will probably only be possible with Node.js since the browser can't create TCP sockets, unless you create an HTTP to SSH proxy, but this is better to have as a separate project.

**Comment by Calisto-Mathias** [comment]
I'd definitely like to work on it. And it does seem like at least for now, this would only be possible on node based applications as TCP sockets on port 22 aren't yet supported in browser environments. Do you have any good points in the code where I can start some work on this?

**Comment by kneczaj** [comment]
If anybody writes node-only, please link your fork here. I would really like to use it.

**Comment by jimothy-tech** [comment]
I've started investigating a Node.js only implementation. Since I see that it's not desired for SSH to live inside of isomorphic-git, I'd like to build off of @mojavelinux's suggestion of focusing on a plugin. If acceptable, I'd like to refactor the library to enable an external, injectable `remoteHelper`.

The supplied helper would implement the same `discover()` and `connect()` contract currently used by `GitRemoteHTTP` and contain its own transport dependencies. When no helper is supplied, the existing HTTP/HTTPS behavior would remain unchanged and continue using the `http` argument for commands such as `fetch({ http })`.

This would avoid adding SSH-specific code or transport selection to isomorphic-git itself:

```javascript
// Import the external plugin factory and client
import { createRemoteHelperSSH, ssh } from 'isomorphic-git-ssh';

const sshRemoteHelper = createRemoteHelperSSH({
    client: ssh,
    privateKey: key    
});

await git.fetch({
    fs,
    url: 'git@github.com:owner/repo.git',
    remoteHelper: sshRemoteHelper,
});
```
It would remain backwards compatible and still allow:

```javascript
await git.fetch({
    fs,
    url: 'https://github.com/owner/repo.git',
    http,
});
```

**Comment by jcubic** [comment]
I'm not sure about the name, but we can handle that later.

You can create a PoC, and we will see.

**Comment by jimothy-tech** [comment]
Naming could for sure change - I don't mind at all. I'll get to work on that PoC.
