### ISSUE TITLE
Pull GitHub Pull Request references

### ISSUE THREAD

**Issue by chadfawcett** [isomorphic-git/isomorphic-git#235]
It appears GitHub pull request references can't be resolved.

```js
git.pull({ fs, dir: './repo', ref: 'pull/1/head' })
//  Error: Could not resolve reference pull/1/head
```

I see the docs don't show a `remote` attribute for `pull`, which felt like an omission to me. I also looked at your tests for a bit of direction, but there are not tests for `pull`.

**Comment by wmhilton** [comment]
A quick workaround is to add a line to the `.git/config` file so that it will fetch PRs by default. Add a line saying `fetch = +refs/pull/*:refs/remotes/origin/pull/*` to the end of the `[remote "origin"]` section  like so:

```
[remote "origin"]
        url = https://github.com/isomorphic-git/isomorphic-git
        fetch = +refs/heads/*:refs/remotes/origin/*
        fetch = +refs/pull/*:refs/remotes/origin/pull/*
```

Then `git.fetch` will fetch all those pull requests by default.

The test for pull is [here](https://github.com/isomorphic-git/isomorphic-git/blob/master/__tests__/server-only.test-pull.js) by the way. Remember it only does fast-forward merges at the moment.

* * *
I think the reason there's no `remote` parameter is that it is currently always considering `ref` to be a local ref, and it is choosing the remote based on the remote tracking branch information in `.git/config`. Which... is probably the wrong thing to be doing except for the default case when `ref = 'HEAD'`. I'll have to experiment with that.

**Comment by chadfawcett** [comment]
Thanks for the quick reply. I was trying something similar that I found in this [gist](https://gist.github.com/piscisaureus/3342247), but was getting a `Error: Invalid refspec` error.

Though this also brings up the issue of setting the config programatically. From my understanding using the `git.config` function will override the existing `fetch` value.

For my use case, this is fine, but maybe I was misunderstanding the docs.
