### ISSUE TITLE
Auth with personal access token

### ISSUE THREAD

**Issue by hirokiosame** [isomorphic-git/isomorphic-git#242]
Is it possible to fetch with a Github Personal Access Token? I don't want to have to create a new account for the server that would be using this module, or add a credential with more permission than it needs. Seems fairly straightforward based on [this](https://blog.github.com/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/) but would like some insight before going down the rabbit hole.

<img width="705" alt="screen shot 2018-05-27 at 8 30 14 pm" src="https://user-images.githubusercontent.com/1075694/40585387-d2b9b486-61ec-11e8-9a7c-49f159a71974.png">

**Comment by wmhilton** [comment]
Yes! I have always used it with a personal access token. I think you just need the basic 'public_repo' permissions (or 'repo' for private repos)... wow it looks like github has gone crazy with fine grained oauth permissions.

**Comment by hirokiosame** [comment]
Ah nice! Would you mind showing me how to pass in a token into clone instead of the login credentials? I don't see it in the [docs](https://isomorphic-git.github.io/docs/clone.html)

**Comment by wmhilton** [comment]
Done in https://github.com/isomorphic-git/isomorphic-git.github.io/commit/6f7dfbd576be969da52fc3f35d6d3adc62edd154

**Comment by hirokiosame** [comment]
Thanks @wmhilton ! The links are nice, but if I may... what might help is elaboration on how to pass `git.utils.auth('personal access token')` into `fetch` or `clone`

**Comment by albinekb** [comment]
@hirokiosame using VS Code I saw the property names, they are passed as `
authUsername` and `authPassword` 

```js 
  let repo = { fs, dir: './' }
  const credentials = git.utils.auth('albinekb', TOKEN)

  await git.clone({
    ...repo,
    authUsername: credentials.username,
    authPassword: credentials.password,
    url: 'https://github.com/...git',
    singleBranch: true,
    depth: 1,
  })```
![image](https://user-images.githubusercontent.com/5027156/41190375-8a16f75c-6bdd-11e8-8f97-75e39e17e523.png)

**Comment by hirokiosame** [comment]
@albinekb Yeah, I had to look at the source to figure it out. But also wasn't sure if that was the expected approach, hence the request for documentation. Hoped for something like this:
```
 git.clone({
    ...repo,
    ...git.utils.auth('albinekb', TOKEN),
    url: 'https://github.com/...git',
    singleBranch: true,
    depth: 1,
  })
```

**Comment by wmhilton** [comment]
Hah! That's funny, I actually thought
```js
git.clone({
  ...git.utils.auth('albinekb', TOKEN),
```
WAS the API. At [one time](https://github.com/isomorphic-git/isomorphic-git/commit/af92e2ec877ab6c1bf6a7bba6708594b178778b3) it was more like
```js
git.clone({
  auth: git.utils.auth('albinekb', TOKEN),
```
and then I flattened the `auth` object into `authUsername` and `authPassword`. Hmm.

I'm with @hirokiosame . I don't like this. This API sucks:
```js
const { username, password } = git.utils.auth('albinekb', TOKEN)
await git.clone({
  authUsername: username,
  authPassword: password,
```

As much as I *conceptually* like exposing the fact that under-the-hood, using OAuth2 tokens are actually just transmitted as Basic Auth just like username/password pairs, because I feel like that makes them seem much less mysterious, maybe it's time to fold the dinky `utils.auth`  and `utils.oauth2` into the base commands.

**Comment by wmhilton** [comment]
All right. Feedback on my idea for simplifying the API?

First of all, `authUsername` and `authPassword` will continue to be available for backwards compatibility, although they will be removed from the TypeScript definitions so that VS Code users (@albinekb so glad that worked for you! I learned how to write TypeScript definitions just so that would work 😁 ) so that VS Code users won't be confused by seeing the old property names along with the new ones. \*

<details><summary>* I suppose that could also mean...</summary> that TypeScript programs won't compile with the new version... but oh well, this is not a TypeScript library. And migrating code will be really simple.</details><br><br>

The new properties will be:
- `username`
- `password`
- `token`
- `oauth2format`: one of the companies listed in [`utils.oauth2`](https://isomorphic-git.github.io/docs/utils_oauth2.html)

And the Basic Auth username and password will be computed as described by the following truth table:

| username | password | token | oauth2format | = Result                                                                                  |
| -------- | -------- | ----- | ------------ | ----------------------------------------------------------------------------------------- |
|          |          |       |              | Basic Auth not used                                                                       |
| X        |          |       |              | Error "Missing token or password"                                                         |
|          | X        |       |              | Error "Missing username"                                                                  |
| X        | X        |       |              | `{authUsername: username, authPassword: password}`                                        |
|          |          | X     |              | Github's alternative form `{authUsername: token, authPassword: ''}`                       |
| X        |          | X     |              | `{authUsername: username, authPassword: token}`                                           |
|          | X        | X     |              | Error "Missing username"                                                                  |
| X        | X        | X     |              | Error "Can't have both token and password"                                                |
|          |          |       | X            | Error "Missing token"                                                                     |
| X        |          |       | X            | Error "Missing token"                                                                     |
|          | X        |       | X            | Error "Missing token"                                                                     |
| X        | X        |       | X            | Error "Missing token"                                                                     |
|          |          | X     | X            | as described in [`utils.oauth2`](https://isomorphic-git.github.io/docs/utils_oauth2.html) |
| X        |          | X     | X            | as described in [`utils.oauth2`](https://isomorphic-git.github.io/docs/utils_oauth2.html) |
|          | X        | X     | X            | as described in [`utils.oauth2`](https://isomorphic-git.github.io/docs/utils_oauth2.html) |
| X        | X        | X     | X            | as described in [`utils.oauth2`](https://isomorphic-git.github.io/docs/utils_oauth2.html) |  |

**Comment by wmhilton** [comment]
Oh, I remember why I flattened it. It was to simplify specifying command line arguments.
