### ISSUE TITLE
Make git.log not include errors for shallow commits and depth not specified

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#245]
If you run git.clone depth: 3 and git.log it return 4 items in array where last item is error:
```
Error: Failed to read git object with oid afcedfd9c8fc8fa1c7a4196cb5e49a0e7a11c464
    at https://cdn.jsdelivr.net/npm/isomorphic-git@0.17.0/dist/bundle.umd.min.js:8:30278
    at Generator.next (<anonymous>)
    at n (https://cdn.jsdelivr.net/npm/isomorphic-git@0.17.0/dist/bundle.umd.min.js:8:28961)
    at https://cdn.jsdelivr.net/npm/isomorphic-git@0.17.0/dist/bundle.umd.min.js:8:29055"
```

**Comment by wmhilton** [comment]
Shallow clone?

**Comment by jcubic** [comment]
I just filter out commits that had error field and it's ok but I think that if git clone was had 3 commits git.log should also return 3 commits.

**Comment by wmhilton** [comment]
I'd happily accept a PR to git.log that adds a check [here](https://github.com/isomorphic-git/isomorphic-git/blob/1977e0b560be33361157045f21e554cd0a1e6b8c/src/commands/log.js#L47) and doesn't append the error to the results if 1) no `depth` argument was specified and 2) the error is of type `Failed to read git object with oid ${oid} because it is a shallow commit`.

Other types of errors would be *real* errors trying to find the parent commit.

**Comment by erdahuja** [comment]
Hi! I would like to address this, but I'm not familiar with the way to do it (first commit), could you guys give me some help?
