### ISSUE TITLE
Can't commit file with error "Could not understand file mode: 0"

### ISSUE THREAD

**Issue by ilDon** [isomorphic-git/isomorphic-git#275]
I'm having some troubles committing files.

After creating the repository, I am able to do a first empty commit. Then I add a file to the staging area (it appears in the list of file with `.listFiles()`), but if I then call `.commit()` the command fails with error  `Could not understand file mode: 0`.

The stranger part is that I've noticed that upon configuration `git.init()` sets `filemode = false`, so I wonder why that is even an issue.

**Comment by wmhilton** [comment]
I will look into filerjs ! Can't promise anything... if I switch from "one supported Browser fs" to "N supported Browser fs" I may never get to sleep... but it may be relatively trivial to either fix Filer's fstat implementation or figure out how to work around it.

I explain [over here](https://github.com/isomorphic-git/isomorphic-git/issues/246) how to get source maps working, which should give you all the benefits of a non-minified UMD version AFAICT.

**Comment by wmhilton** [comment]
It look like [here](https://github.com/filerjs/filer/blob/c8f217fbcd6a7e802b68c5ba213c0b8d864aeadc/src/stats.js#L3) their Stats implementation simply isn't returning any `.mode`. :( 

Wow, to the path I traced is during git add:
stats has no mode. so `stats.mode` is `undefined`.
`stats.mode % MAX_UINT32` is `NaN` (because JavaScript)
`buffer.writeUInt32BE(NaN, n)` writes a `0` into the buffer for some reason?!

Then it's a straightforward path from there on through `git.commit`, as the value that actually got stored in the git index is indeed 0.

Sadly, it doesn't look like the authors of FilerJS are actively maintaining it, so I doubt I'd be able to get in a PR to fix their 'mode' value.

Would you be up for hacking around it? Really we just need just need to wrap the... eh, no wrapping functions that take callbacks is annoyingly hard, plus there's like 3 variants `lstat`, `stat`, and `fstat`.

I'm just going to add a default fallback value for `mode` if it's undefined when adding it to the git index. That ought to do the trick.

**Comment by ilDon** [comment]
Great! Many many thanks!!
