### ISSUE TITLE
git.add adds wrong filepath when filepath is multibyte string (like Japanese)

### ISSUE THREAD

**Issue by mizchi** [isomorphic-git/isomorphic-git#354]
I encountered on Node@10, Chrome 68 and isomorphic-git@0.24.2

```js
  const root = '/my-root'
  const addingFilepath = "日本語"
  await fs.promises.writeFile(path.join(root, addingFilepath), "1")
  await git.add({ fs, dir: root, filepath: addingFilepath })
  await git.commit({
    fs,
    dir: root,
    message: "Add japanese file",
    author: { email: "dummy", name: "dummy" }
  })
  const files = await git.listFiles({ fs, dir: root })
  console.log(files)
```

This result lost some data

```
 [ '日' ] // expected:  ['日本語']
```

**Comment by mizchi** [comment]
Now I doubt around https://github.com/isomorphic-git/isomorphic-git/blob/master/src/models/GitIndex.js#L94-L102

**Comment by wmhilton** [comment]
Thank you! That's a good bug to find.

I'm thinking it is probably actually https://github.com/isomorphic-git/isomorphic-git/blob/master/src/models/GitIndex.js#L220 (maybe in a few more places)

the problem is straightforward:
```js
> "日本語".length
3
> Buffer("日本語").length
9
```

so I probably need to use the latter instead of the former in a few places.

**Comment by wmhilton** [comment]
Ah yes. It's not because it was under a directory per se, but due to the length of the filename. Thank you for the fix!
