### ISSUE TITLE
should not fail with E.PushRejectedNonFastForward if no new commits to push

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#398]
Probably happening because the remote head is NOT technically a descendent of the local head. It's the same commit.

It should go ahead and allow the push, because IDK, lets you trigger remote hooks or whatever.

**Comment by strogonoff** [comment]
Ran into this too. In my sync logic (which runs only in absence of unstaged/uncommitted changes) I just run pull first to catch any _actual_ fast-forward fails, and then simply ignore `PushRejectedNonFastForward` on subsequent push.

**Comment by strogonoff** [comment]
I’d like to add a note to documentation; but the [errors page](https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/docs/errors.md) seems to be auto-generated from [GitError](https://github.com/isomorphic-git/isomorphic-git/blob/92a7e8333e1c1565286bb09a178cb8a34e8054ce/src/models/GitError.js).

I’d change the message to something like “Push rejected because it was not a simple fast-forward. Use "force: true" to override. Note: an absence of commits to push currently results in this error as well.”, but it seems a bit too long

**Comment by strogonoff** [comment]
(I believe the best way to check whether there is _actually_ something to push should be inspecting `listServerRefs()`)

**Comment by acailly** [comment]
If it can be useful for others, I solved it like that:

```
  const remoteCommits = await git.log({
    fs,
    dir: folder,
    depth: 1,
    ref: `refs/remotes/${remoteName}/${remoteBranch}`,
  });
  const remoteOid =
    remoteCommits && remoteCommits.length ? remoteCommits[0].oid : null;
  const localCommits = await git.log({
    fs,
    dir: folder,
    depth: 1,
  });
  const localOid =
    localCommits && localCommits.length ? localCommits[0].oid : null;
  if (localOid === remoteOid) {
    return;
  }
```

**Comment by Vinzent03** [comment]
I think it's more efficient to get the SHA-1 object by using `git.resolveRef()`.
```ts
```

**Comment by mojavelinux** [comment]
It turns out that logic is already done in the _push function. All we need to do is add an equality check.

**Comment by mojavelinux** [comment]
I think this should be a bug since it differs from the behavior of canonical git. I can push as many times as I want with canonical git and it doesn't complain.

**Comment by mojavelinux** [comment]
I submitted a PR with the proposed fix. See #1625
