### ISSUE TITLE
Expose response headers

### ISSUE THREAD

**Issue by juancampa** [isomorphic-git/isomorphic-git#500]
In my project, users deploy simply by pushing their code, the server builds it and deploys it and sends back the deployment data back to the client. Currently I'm parsing the `message` event which is not super robust. A better approach would be to return data in an HTTP header but those are not exposed for `fetch`/`pull`/`push`.

Do you think it would make sense to expose the HTTP in the results of network operations?

Once again, thanks @wmhilton!

**Comment by wmhilton** [comment]
Interesting. The `message` event seems much simpler... I'm worried that a solution using HTTP headers would run into CORS problems, since you'd have to modify the cors proxy to include your custom header in the `Access-Control-Allow-Headers` header.

That being said... you might be able to work around this using the [httpAgent plugin](https://github.com/isomorphic-git/isomorphic-git/pull/393) proposal? I'm not sure.

Another idea I'm thinking about is removing the dependency on `simple-get` and allowing the HTTP library to be injected via a plugin, e.g. `plugins.set('fetch', window.fetch)` or `plugins.set('fetch', require('node-fetch'))`. We could also use the plugin system to inject a "mock" HTTP request library which would make the tests more robust!

Do you know _why_ the message event is not "super robust"? If it's flakiness on the client side then maybe we can just improve the robustness on the client side.

**Comment by juancampa** [comment]
To be clearer, this is what I'm thinking:

Instead of:
```
const { ok, errors } = git.push(...);
const deploymentID = /* parse value from messages */
```
I want to do this something like this:
```
const { ok, errors, response } = git.push(...);
const deploymentID = response.headers[`X-Deployment-ID`]
```
(my server sets this header)

More generally, it'd be useful to have access to the HTTP headers returned the POST to `/git-receive-pack` next to the standard `ok` and `errors`. I'm not using a cors proxy so, in my case, it wouldn't be a problem

> Do you know _why_ the message event is not "super robust"?

To be clear, it's not a problem with `isomorphic-git`. Our git server sends messages meant to be read by users and it even includes text controlled by the user (e.g. it prints filenames as they are being transpiled). It looks like this:
```
...
Transpiling:
  - index.js... OK
  - file2.js... OK
Deploying...
Done.
Deployment ID: <id>
```

So the client looks for `^Deployment ID: (<id>)$`. This works but I'm not a fan of mixing human-readable data with machine-readable data.

**Comment by wmhilton** [comment]
Ah... makes perfect sense. I just need to think about how this interacts with my plans to support other transport mechanisms besides HTTP. If the git remote is being connected to via SSH or DAT for instance.

I might make it return _just_ the headers, like:
```js
const { ok, errors, headers } = git.push(...);
const deploymentID = headers[`X-Deployment-ID`]
```
rather than the full `response`. The `headers` is guaranteed to be a simple JSON object, whereas the `response` object has a lot more exposed API.

Or if I can figure out how to abstract this all behind an `http` plugin, I might do that.

**Comment by juancampa** [comment]
> I might make it return _just_ the headers

That works too. Thanks for the quick turnaround!

Closing this in favor of #502

**Comment by wmhilton** [comment]
I want to wax philosophically a bit about this decision.

I decided that at its core, the problem is "how can we capture data sent through the side-channel of the transport that's not part of the git protocol proper"? And the nature of that problem is a hack. The need for it is straightforward: the git protocol is designed to support adding features in a forwards and backwards compatible manner, but it does NOT lend itself easily to vendor-specific additions. As you've discovered, the only way to hijack and inject this data would be using the `post-receive` hook, but doing this mixes your data with git's own status messages! This becomes a nightmare to parse.

Although............... now that I think about it........ have you considered newline-delimited JSON? That might actually work semi-elegantly:
```js
emitter.on('message', (message) => {
  try {
    // is it fancy vendor data?
    data = JSON.parse(message)
    if (data.deploymentID) {
      // do something with the deployment id
    } else if (data.transpiling) {
      // print the name of a transpiling file
      process.stdout.write(`  - ${data.transpiling}... `)
    } else if (data.transpileOK) {
      process.stdout.write(` OK\n`)
    }
  } catch (err) {
    // nope it's just a git message
    console.log(message)
  }
})
```

OK well... I shot my own foot now. I _was_ going to say that this is so difficult, that it necessitates using a side-channel, and that the details for that side-channel are going to be different for every possible transport - HTTP, SSH, WebSockets, BitTorrent, IPFS, SSB, dat, and so on. Therefore there is no "elegant" universal way to solve it for every such case, and we'll just need to include hacks (like returning HTTP headers) as needed.

Meh. Too late I already merged it. I guess my argument now is: some extra HTTP headers in the return value from `fetch` and `push` aren't going to hurt anything.

**Comment by juancampa** [comment]
It seems like the git client handles it as a protocol error: https://github.com/git/git/blob/7e8bfb0412581daf8f3c89909f1d37844e8610dd/sideband.c#L202-L205

**Comment by wmhilton** [comment]
Oh hey! I don't know if this is useful to you, but it looks like `git` also allows you to _send_ extra headers!

https://git-scm.com/docs/git-config#git-config-httpextraHeader

Let me know if you need that feature. It shouldn't be too hard to implement.

**Comment by juancampa** [comment]
Yeah I use that for my cli client to send auth and metadata that shouldn't
be version controlled. I'm about to implement this on the web version so
I'll be indeed needing it pretty soon! Thanks for preemptively asking
