### ISSUE TITLE
Phase out 'simple-get'

### ISSUE THREAD

**Issue by billiegoose** [isomorphic-git/isomorphic-git#600]
it's been a good run. But it's time to let go of the dependency on the 'http' and 'https' node builtins that have to be shimmed. context: https://github.com/isomorphic-git/isomorphic-git/issues/597#issuecomment-443276722

maybe isomorphic-fetch?

**Comment by mojavelinux** [comment]
Incidentally, I was just talking about phasing out simple-get in relation to another issue earlier today. I found that it's not handling redirects in a way that is compatible with what isomorphic-git is trying to do. It's because simple-get changes the HTTP method when redirecting, which breaks the POST request that isomorphic-git attempts to send. It comes down to feross/simple-get#35.

I've had a lot of success with got. Perhaps consider [Ky](https://github.com/sindresorhus/ky), maintained by the same author who does the hugely popular got library.

**Comment by wmhilton** [comment]
I don't think we'd want to use Ky simply because it looks like it's trying to be _helpful_ out of the box, and I've found those tend to be harder to work with. For instance, we'll probably want manual HTTP redirect handling, see https://github.com/isomorphic-git/isomorphic-git/issues/199#issuecomment-397102702

**Comment by wmhilton** [comment]
Possible plugin design:
```ts
interface FetchOptions {
  method?: string = 'GET';
  headers?: {
    [key string]: string
  } = {};
  body?: Stream;
}

interface FetchResult {
  status: number;
  headers: {
    [key string]: string
  };
  body?: Stream;
}

const fetch: (url: string, options: FetchOptions) => FetchResult

git.plugins.set('fetch', fetch)
```

I'm currently using [stream-source](https://www.npmjs.com/package/stream-source) to wrap the streams, so it should work with both [Node streams](https://nodejs.org/api/stream.html) and [Browser streams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream).

**Comment by wmhilton** [comment]
Ugh. Streams are so much harder than they should be. Fun fact, the browser can't stream uploads. 😱

**Comment by wmhilton** [comment]
@mojavelinux Did you file an issue for the redirect issue? I'm trying to keep track of all the problems we can solve with #605 - assuming I design the API around the HTTP request plugin correctly.

I think the plugin would also let someone hack their way around #386.

**Comment by wmhilton** [comment]
@mojavelinux I have an idea for how to fix the redirect issue. Git precedes each POST request with a GET request, so we could resolve redirects during the first GET request by saving the returned `res.req.path` and use that new path for subsequent POST requests.

**Comment by mojavelinux** [comment]
> Git precedes each POST request with a GET request, so we could resolve redirects during the first GET request by saving the returned res.req.path and use that new path for subsequent POST requests.

Brilliant!

**Comment by mojavelinux** [comment]
> @mojavelinux Did you file an issue for the redirect issue?

I've been super busy, so I forget. I just did it. See #671. I also posted your proposed solution.
