### ISSUE TITLE
Add feature to check whether HEAD is detached

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#622]
When working with branches, it's sometimes necessary to know when the repository is not on a branch (detached HEAD). Add a feature to check for this state.

The most logical place for this would be currentBranch, IMO. If the repository is not on a branch, this function should return a falsy value (perhaps undefined). (If you really want the commit of the detached HEAD, you can use resolveRef directly).

**Comment by wmhilton** [comment]
That sounds about right. Otherwise you'd have ambiguity if you were on a branch called `f44ad41afb57563e9e93a6343a6957798d474a8e` for instance.

I've always hated working in a detached head state. It's such a terrifying name.
![999827_10151445292510936_1210528904_n](https://user-images.githubusercontent.com/587740/49677853-ee777780-fa4e-11e8-9b2a-589f2cda4f2b.jpg)
(Holy crap I look so young back then)

**Comment by wmhilton** [comment]
For the curious, that is not photoshop. That was an optical illusion in a science museum where you could stick your head up out of the "table". It's not a real table - it's actually a solid box painted to look like a table with empty space underneath it..
