### ISSUE TITLE
Naming things consistantly

### ISSUE THREAD

**Issue by wmhilton** [isomorphic-git/isomorphic-git#631]
I have tried REALLY hard to be consistent with how I name things throughout the API so there are no surprises. But a few inconsistencies have come to my attention:

Files (in the index)
- add({ filepath })
- remove({ filepath })
- listFiles({ })

Branches
- branch({ ref }) _(why isn't this argument `branch`?)_
- deleteBranch({ ref })
- listBranches({ })

Remotes
- addRemote({ remote }) _(why isn't this called `remote`?)_
- deleteRemote({ remote })
- listRemotes({ })

Tags
- TBD
- TBD
- listTags({ })

There's a few competing goals:
1. Consistency with canonical git. Examples:
  - `add` = `git add`
  - `remove` = `git rm`
  - `listFiles` = `git ls-files`
  - `branch` = `git branch`
2. Self-consistency (made difficult because canonical git is inconsistent). Examples:
  - `addFile({ file })` would be consistent with `addRemote({ remote })`
  - `addBranch({ branch })` would be consistent with `addTag({ tag })`

@mojavelinux @yuhr @juancampa which style do you prefer? (If we change anything, we would add aliases for arguments / function names to preserve backwards compatibility for the 0.x series as always!)

Edit: I guess the third category is some kind "internal consistency" as illustrated later in https://github.com/isomorphic-git/isomorphic-git/issues/631#issuecomment-445982230

**Comment by mojavelinux** [comment]
My first bit of advise is something general. Try to be consistent, but don't overthink it. I've seen projects that were so worried about getting naming right that it no longer felt nature. So you get the big stuff right and let the little stuff just be part of the flavor.

> made difficult because canonical git is inconsistent

Isn't that the truth!

For functions like `branch`, we should decide whether the primary argument should match the function name (i.e., `branch`) or use the generic term `name`. In other words:

a) branch({ ...repo, branch: 'foobar' })
b) branch({ ...repo, name: 'foobar' })

Neither is more correct. Let's just find our style. I'm leaning more towards (b), but I could throw my vote either way.

For functions that add, I think we should either use the `add` prefix or no prefix.

a) addRemote({ ...repo, remote: 'fork' })
b) remote({ ...repo, remote: 'fork' })

In this case, being consistent with the git command feels the most right (b). I feel pretty strongly about that as the add prefix feels dirty to me.

When a command in git is abbreviated (like rm or ls-files), I think isomorphic-git should spell them out (like remove and listFiles). I don't much like abbreviations in function names. It's too cute.

**Comment by yuhr** [comment]
Hmmm, I agree with @mojavelinux in general...

As for param names' matter, personally speaking I prefer `name` in such case, because it's more specific about "what to put" as the argument (so, for example, I might as well have `writeRef` taking `path` instead of `ref`).  But I see there has already been some convention naming by "what to put the name of" (`branch`, `resolveRef` and some others are the ones). Do we deprecate agressively, as the version is under 0.x yet? 😜 

And, I feel prefixes are always dirty. 🤣 But appropriate prefixes are really informative from the users' point of view. Come to think of it, in the case of the concerned functions such as `tag`, we might as well rename like `addTag` because they are only for creating and not deleting unlike canonical git. (When first time I had implemented tag deletion, I was planning on integrating it into the `tag` command but stopped on the second thought seeing `deleteBranch`)

Note that we have `resolveRef` and `readObject` which we were able to make their name definitely more easy to know what the APIs do than the canonical `cat-file`, this is just because we made them with _separation of concerns_. Obviously this naming is inconsistent with the canonical but user-friendly. With regard to this point I think the canonical commands are misdesigned i.e. `remote` has descriptive subcommands such as `add` and `remove`, while `tag` and `branch` don't. We don't have to inherit such inconsistency.

If we use prefixes there might be another thing to add to this topic: which one we should use, `add` or `create` or `write`? My proposal is:

- Use `add` for **files** and **remotes**; because the entities exist already before API call
- Use `create` for **tags** and **branches**; because these are just constructed by API call
- Use `write` for **refs** and **objects**; because these are low-level things

**Comment by mojavelinux** [comment]
> we might as well rename like addTag because they are only for creating and not deleting unlike canonical git.

This is a great point. I hadn't though of it that way.

> We don't have to inherit such inconsistency, and in this case I prefer subcommands.

Also a great point.

**Comment by wmhilton** [comment]
Ah. To muddy the waters a bit, I remember now why the argument to `remote` is `remote` and the argument to `branch` is `ref`: re-usability of the params:

```js
let ref = 'new-branch'
await git.branch({ dir, ref })
await git.checkout({ dir, ref })
await git.push({ dir, ref })

let remote = 'upstream'
let url = 'https://github.com/isomorphic-git/isomorphic-git'
await git.addRemote({ dir, remote, url })
await git.fetch({ dir, remote })
await git.checkout({ dir, ref, remote })
```

So by this logic... really the argument to `tag` should _also_ be `ref`.

**Comment by wmhilton** [comment]
> we might as well rename like addTag because they are only for creating and not deleting unlike canonical git

That's a pretty good point. I made creating and deleting separate functions so a) you don't accidentally do the wrong thing and b) the type signatures are simpler (one function per one thing).

> `readObject` which we were able to make their name definitely easier to know what the APIs do than the canonical `cat-file`

Thank you for recognizing this! Yes, `readObject({ format: 'parsed' })` is essentially `git cat-file -p` but with a less ridiculous name.

I felt like I could have more freedom to ditch the canonical plumbing commands in favor of new (better-named) plumbing commands... because if you're diving into the plumbing commands you likely are reading the docs anyway. The porcelain commands I tried to keep closer to the canonical porcelain command names, because I wanted people to be able to "just wing it" and type some code using nothing but auto-completion and get reasonable results.

**Comment by wmhilton** [comment]
> Try to be consistent, but don't overthink it. I've seen projects that were so worried about getting naming right that the API no longer felt natural. So you get the big stuff right and let the little stuff just be part of the flavor.

I think you're right. I think the use of `ref` may just be part of the "flavor" of isomorphic-git. See how naturally this works:
```js
let ref = 'v1.0'
await git.tag({ dir, ref }) // add tag
await git.verify({ dir, ref }) // verify tag
await git.push({ dir, ref }) // push tag
```
compared with the alternative:

```js
let ref = 'v1.0'
await git.addTag({ dir, name: ref }) // add tag
await git.verify({ dir, ref }) // verify tag
await git.push({ dir, ref }) // push tag
```

**Comment by wmhilton** [comment]
but I might alias `remote` to `addRemote`.

**Comment by mojavelinux** [comment]
> I think the use of ref may just be part of the "flavor" of isomorphic-git.

Good call! Your reasoning is sound. And in at least a few cases, I've though to myself "well, the option is probably `ref`, so let's try that first". And sure enough, it works. So it's the right kind of consistently.

> but I might alias remote to addRemote.

If you are sticking with addTag, then I strongly support this alias.

**Comment by yuhr** [comment]
> I think the use of `ref` may just be part of the "flavor" of isomorphic-git.

Now I see that's reasonable too. 👍 

> Yes, readObject({ format: 'parsed' }) is essentially git cat-file -p but with a less ridiculous name.

And not only about naming, you note that `cat-file` also *resolves* refs if passed, while `readObject` accepts only oids (this kind of design seems pretty good to me). That's why I also mentioned to `resolveRef` and SoC here, and I thought the same applies to kind of `add`-`delete` pair. Though, I also appreciate this:

> The porcelain commands I tried to keep closer to the canonical porcelain command names, because I wanted people to be able to "just wing it" and type some code using nothing but auto-completion and get reasonable results.

That said, why don't we have both prefixed or non-prefixed ones for `add`ing commands, not either? 😉

> but I might alias remote to addRemote.

I really support that!

**Comment by yuhr** [comment]
That's also good surely, I don't oppose to your choice. 👍

**Comment by wmhilton** [comment]
> In that vein, I'll rename `addRemote` to `remote` and update it in the docs. Then for 0.x we'll just export it with two names, the old one and the new shorter one.

Finally started on this today and ran into a slight problem... `remote` is one of the arguments to `addRemote`. I can't rename `addRemote` to `remote` without destroying the nifty shorthand argument pattern. 😢

```js
let remote = 'upstream'
await addRemote({ dir, remote, url })
// vs
let name = 'upstream'
await remote({ dir, remote: name, url })
```
 
And I can't rename the `remote` argument to something like `name` without destroying the nifty shorthand argument pattern for all the _other_ functions that use a `remote` parameter:
```js
let remote = 'upstream'
await addRemote({ dir, remote, url })
await push({ dir, remote })
// vs
let name = 'upstream'
await remote({ dir, name, url })
await push({ dir, remote: name })
```

These problems don't happen with `tag` or `branch` exactly because they _don't_ call their main parameter `tag` and `branch`, they call it `ref`.

One of the reasons I use this shorthand api style throughout, with named arguments instead of positional arguments, is to alleviate users from having to name things themselves. If I introduce a name conflict for the sake of consistency, then users will have to a) decide whether to alias remote-the-function or remote-the-parameter and b) pick some alias.

Example: alias remote-the-function to 'createRemote':
```js
let remote = 'upstream'
import { remote as createRemote } from 'isomorphic-git';

await createRemote({ dir, remote, url })
await push({ dir, remote })
```

Example: alias remote-the-parameter to 'remoteName':
```js
let remoteName = 'upstream'
import { remote } from 'isomorphic-git';

await remote({ dir, remote: remoteName, url })
await push({ dir, remote: remoteName })
```

and now whoever reads their code - even if they're familiar with isomorphic-git, won't be familiar with the names `createRemote` or `remoteName` and that'll cause extra friction.

So to spare everyone having to make these choices, I'll decide *this* is the "canonical" naming choice:

```js
import { remote as addRemote } from 'isomorphic-git';
```

...and enforce it by... leaving the `addRemote` function named `addRemote` instead of changing its name. 😞 Let it be known that I tried.
