### ISSUE TITLE
Add flag to force branch creation

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#639]
The use case I'm trying to address is to either create a branch and switch to it or just switch to it if it already exists. It's the functional equivalent of:

```js
await git.branch({ ...repo, ref: 'branchname', checkout: true })
  .catch((e) => {
    if (e.code === git.E.RefExistsError && e.data.noun === 'branch') {
      return git.checkout({ ...repo, ref: 'branchname' })
    }
    throw e
  })
```

However, that's not idiomatic. It also requires some work to avoid calling checkout with side effects (the creation of a remote tracking branch).

What I'd like to be able to do is force create the branch:

```js
await git.branch({ ...repo, ref: 'branchname', force: true })
```

which is the same as `git branch -f branchname`.

which I can then combine with the checkout option to checkout the branch at the same time:

```js
await git.branch({ ...repo, ref: 'branchname', checkout: true, force: true })
```

which is the same as `git checkout -B branchname`.

The `force` flag would thus allow isomorphic-git to cover both use cases.

**Comment by mojavelinux** [comment]
I'm also somewhat interested in a flag on the checkout function that disables the automatic remote tracking branch feature, though I can't find anything equivalent to that in the native git command.

**Comment by wmhilton** [comment]
> or just switch to it if it already exists.

I don't think `force` would do that would it? Wouldn't `force` forcefully overwrite the branch to point at `HEAD`?

**Comment by wmhilton** [comment]
By the way... the way you mixed `await` with `.catch()` makes me dizzy lol.

**Comment by mojavelinux** [comment]
> Wouldn't force forcefully overwrite the branch to point at HEAD?

Oops, you're absolutely right!

**Comment by wmhilton** [comment]
OK that makes a lot more sense!

**Comment by wmhilton** [comment]
But I'm confused because then `--checkout --force` doesn't solve your initial use case:

> The use case I'm trying to address is to either create a branch and switch to it or just switch to it if it already exists.

**Comment by wmhilton** [comment]
If that's the use case you're actually trying to achieve, I'm wondering if a `createIfMissing` option for `checkout` makes more sense?

**Comment by wmhilton** [comment]
@mojavelinux what do you think?

**Comment by wmhilton** [comment]
Hmm. I don't like that solution, because I've had bad experiences creating optional arguments the default to `true` (like this `reset` argument).

It also seems complicated. Every time you add a boolean option, you double the complexity of a function. If you think about it, a single function with 3 boolean options is equivalent to 8 functions. (Or one switch statement with 2^3 cases.) Out of all 8 combinations of `checkout`, `force`, and `reset` - how many behaviors do we actually care about?

Side note: I made this explicit one time in [calculateBasicAuthUsernamePasswordPair](https://github.com/isomorphic-git/isomorphic-git/blob/master/src/utils/calculateBasicAuthUsernamePasswordPair.js) and somebody tweeted it as exceptionally clever.

Let's sit on this for a bit and see if we can come up with a simpler solution.

**Comment by mojavelinux** [comment]
$subject was implemented some time ago. The `force` flag lives. The conversation diverged, but it warrants a separate issue if there is still a need.
