### ISSUE TITLE
Writing an executable file to workdir should honor umask

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#640]
When a regular file is written, it uses the umask (since non permissions are specified). However, when an executable file is written, it's always written using 0o755, ignoring the umask. It should be one way or the other.

The native git command always honors the umask. However, given the isomorphic nature of this project, I'd be happy if files were always written with a fixed permission (i.e., 0o644 for regular files).

**Comment by mojavelinux** [comment]
The simple fix for this is to pass the mode as 0o777. Then, Node will automatically combine it with the umask to produce the proper file permission.

**Comment by wmhilton** [comment]
Congratulations @mojavelinux ! You've out-nerded me. I have only a vague clue what you're talking about.

Could you paste some terminal output using `git` and `isogit` and `ls -l` to demonstrate what `git` is doing differently? (I'm guessing if you do `checkout` with each you get different permissions?) I'm using 755 because that's the value literally stored in tree objects for executable files if you look at the output of `git cat-file -p <some tree SHA>` but I will understand if that really just means "executable" and "normal file".

Meanwhile I'll pull out my Mac and see if I can figure out what you're talking about. :)

**Comment by mojavelinux** [comment]
> You've out-nerded me.

Wow, that's pretty hard to do. I must just be lucky today. :wink: 

So git uses 755 rather arbitrarily to mean "executable". They could have picked 777, 775, or 755. They choose one and went with it as a symbolic value. (Honestly, 777 would have been a better choice, IMO).

When writing an executable file in *nix, complying software should use 777 and allow the umask (user mask) value to filter it. In other words, 777 + umask value = actual permissions of file.

My umask is 0002. So if the software uses 777 as the mode, my system will actually write the file as 775. If I changed my umask to 0022, then my system would write the file as 755. This is why I say that the behavior is *nix compliant. If the goal is to be compliant with the native git command, we should do it this way.

A simple way to test is to put an executable file in a git repo and commit it to GitHub. First, run `umask 0002` and clone the repo. You'll see that the file is written as 775. Now, run `umask 0022` and clone the repo again. You'll see that the file is written as 755.

**Comment by wmhilton** [comment]
Cool! I can reproduce those results. 👍 And confirm that your PR bring the behavior in line with canonical git. 💯

**Comment by mojavelinux** [comment]
Thanks @wmhilton!
