### ISSUE TITLE
WORKDIR tree in walkBeta1 not working

### ISSUE THREAD

**Issue by tilersmyth** [isomorphic-git/isomorphic-git#692]
Using in Node project as a potential replacement for Nodegit. 

I'm unable to pinpoint the exact problem here, but walkBeta1 works fine for me with TREE and STAGE, but when using WORKDIR it throws "TypeError: Cannot read property 'map' of undefined".

statusMatrix also works as expected (including WORKDIR in the matrix). In attempting to troubleshoot, I logged the variables (dir, gitdir) as statusMatrix used them with walkBeta1. I copied the variables exactly and tried using directly with walkBeta1 but still received the "TypeError: Cannot read property 'map' of undefined" error.

Again, I haven't been able to pinpoint directly, but it seems the undefined error is originating from:
https://github.com/isomorphic-git/isomorphic-git/blob/1e78ef2553ddf14fe1a4cf5949b369aa256f1bf4/src/commands/walkBeta1.js#L35-L37

If I pass through the following two trees: [TREE, WORKDIR] and run:
```
console.log(await walkers[0].readdir(entry[0]));
```

I get TREE results as expected, but when I run:

```
console.log(await walkers[1].readdir(entry[1]));
```
nothing is returned;

I could be making a silly implementation error here, but I've been struggling long enough to make me think it could be a bug. Any guidance would be appreciated!!

**Comment by wmhilton** [comment]
Sorry for the delayed response!

I think I'd need to see more of the code to figure out the problem. The "TypeError: Cannot read property 'map' of undefined" error makes me think the error is coming from line 41:

https://github.com/isomorphic-git/isomorphic-git/blob/1e78ef2553ddf14fe1a4cf5949b369aa256f1bf4/src/models/GitWalkerFs.js#L39-L45

which makes me wonder... if `fs.readdir` isn't returning `null`, and isn't returning an Array (because if names is an array `names.map` wouldn't error)... what could it be returning?

OH nooooo... OK, I've figured it out. :embarassed_grin: WORKDIR is expecting `fs` to be a `FileSystem` object (hence the fancy `await fs.readdir()`) and for some reason I forgot to add a wrapper. Every other user-facing function like `statusMatrix` wraps node's native `fs` like this:

https://github.com/isomorphic-git/isomorphic-git/blob/1e78ef2553ddf14fe1a4cf5949b369aa256f1bf4/src/commands/statusMatrix.js#L29

I just need to add a wrapper line like that to the `WORKDIR`, `TREE`, and `STAGE`. TREE happens not to throw an error because it doesn't call `fs.readdir` directly like WORKDIR does.
