### ISSUE TITLE
Is there existing cors-proxy for GitLab?

### ISSUE THREAD

**Issue by licaomeng** [isomorphic-git/isomorphic-git#810]
I wanna use isomorphic-git to clone code from our company's GitLab. But I encountered a cross-origin problem. So is there existing cors-proxy for GitLab like https://cors.isomorphic-git.org for GitHub to solve the cross-origin problem?

**Comment by wmhilton** [comment]
> our company's GitLab

So https://cors.isomorphic-git.org works fine with https://gitlab.com. If you're running into a problem it could be because your company's on-premise GitLab server isn't accessible from isomorphic-git.org's server.

I'd strongly recommend if you're using isomorphic-git with an on-premise GitLab that you setup your own CORS proxy server, using https://github.com/isomorphic-git/cors-proxy. It's relatively easy to incorporate into any existing Node server application.

**Comment by jcubic** [comment]
I have my own php proxy that I use with my Git Terminal and it don't work with gitlab, I have domain filters but gitlab.com is on the list, I'm not sure what is happening maybe User-Agent or other limitation like in GitHub. Not sure what to check to see what's happening.

**Comment by jcubic** [comment]
I'm not sure what changed but now it works, https://jcubic.github.io/git/ tested with some random public repo, I'm not sure about private repos.

**Comment by licaomeng** [comment]
> > our company's GitLab
> 
> So https://cors.isomorphic-git.org works fine with https://gitlab.com. If you're running into a problem it could be because your company's on-premise GitLab server isn't accessible from isomorphic-git.org's server.
> 
> I'd strongly recommend if you're using isomorphic-git with an on-premise GitLab that you setup your own CORS proxy server, using https://github.com/isomorphic-git/cors-proxy. It's relatively easy to incorporate into any existing Node server application.

I set up my own proxy in company's intranet environment, I am able to perform 'git clone' now.

**Comment by wmhilton** [comment]
> I set up my own proxy in company's intranet environment, I am able to perform git clone now.

I'll consider that a win! 🙂
