### ISSUE TITLE
TypeError is thrown during clone when permission is denied to repository on BitBucket

### ISSUE THREAD

**Issue by mojavelinux** [isomorphic-git/isomorphic-git#911]
A TypeError is thrown during clone under the following circumstances:

* The repository is hosted on Bitbucket.
* The credentials (user:password) must be valid for an existing account on the server.
* The account must not have access permission to the repository.

The problem seems to be in the capabilities negotiation.

Here's the stack from the error:

```
Caused by: TypeError: Cannot read property 'split' of undefined
    at parseRefsAdResponse (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5123:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.discover (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5241:26)
    at async fetchPackfile (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6041:22)
    at async fetch (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:5902:22)
    at async Object.clone (/mnt/c/Users/ecroc/git/external/antora/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6413:42)
```

**Comment by mojavelinux** [comment]
I have not been able to reproduce this myself. Here's sample code for someone who wants to test this.

```js
const fs = require('fs')
const git = require('isomorphic-git')

;(async () => {
  await git.clone({
    fs, 
    dir: 'repo',
    url: 'https://bitbucket.org/username/repo.git',
    username: 'username',
    password: 'password',
  })
})()
```

**Comment by mojavelinux** [comment]
It turns out, this may not have to do with BitBucket at all.

The line number refers to isomorphic-git 0.67.5. It's the following line in the parseRefsAdResponse function.

```
capabilitiesLine.split(' ').map(x => capabilities.add(x));
```

In certain circumstance it seems, capabilitiesLine can be undefined.

Maybe it has to do with this comment?

```
// In the edge case of a brand new repo, zero refs (and zero capabilities)
// are returned.
```

**Comment by djencks** [comment]
I think Ec Roc's specific error was caused by lineTwo not having a `\0` in it, resulting in capabilitiesLine being undefined.

cf https://github.com/isomorphic-git/isomorphic-git/pull/922

**Comment by djencks** [comment]
Ec Roc has reproduced the original situation in Antora using my patched isogit and now the message is:
```
error: Expected "Two words separated by ''" but got "ERR Repository not found
The requested repository does not exist, or you do not have permission to
access it.
"
```
The `''` showing up in the expected half indicates that the \0 separator was missing. 
It would certainly be possible to have a more informative description of \0 here, is it worth it? At the moment I'm leaning towards passing in something to print rather than trying to convert the char \0 to a meaningful string.

**Comment by mojavelinux** [comment]
I've been able to create a test in Antora that emulates this error:

https://gitlab.com/antora/antora/blob/53e4c9cf398d7d698191d62c1ed6e45e17227f04/packages/content-aggregator/test/aggregate-content-test.js#L3090-3099

Here's the response from the server that will trigger this error:

```
001e# service=git-upload-pack
0007ref
```

As @djencks points out, notice the absence of the null character in the first ref/capabilities line.

**Comment by wmhilton** [comment]
Before I merge #922 ... would it be more useful if instead of throwing it parsed successfully?

**Comment by wmhilton** [comment]
I'll throw up a branch...

**Comment by wmhilton** [comment]
Can Ec Roc try using this branch? My thought it by avoiding a response parsing error, maybe that'll result in a nicer error, like an HTTP Access Denied error or something?

**Comment by djencks** [comment]
We know what response Ec Roc got from the git server, so perhaps we should have a test with that response?
```
001e# service=git-upload-pack
ERR Repository not found
The requested repository does not exist, or you do not have permission to
access it.

```

My main concern here is that if we (i.e., isomorphic git) receive something we don't 100% understand from the git server, we transmit that information complete and unmodified, with appropriate context information, to the caller.  I haven't tried writing a test yet but after briefly looking at the diff I think perhaps William's proposal would more or less ignore the response above and that there are at least two further unchecked spilts that could, with unexpected input, still give misleading and uninformative errors.   Perhaps later I'll have time to write a test using the server response above to see what happens.

**Comment by mojavelinux** [comment]
@djencks I don't think we have to test every permutation, as a unexpected response is an unexpected response. The crux of the issue here seems to be that the server sends the right first line back, but then puts an error message in the second line. So just as the syntax of the first line is validated, the syntax of the second line should be validated too. And it kind of already is. The only problem is that the code assumes the second like has a `\x00` character, when that is not always the case.

> we transmit that information complete and unmodified, with appropriate context information, to the caller

I suppose when either of the lines is not valid, the error message could just pass along the lines as received somewhere in the error message. Kind of like "I don't know what this is, but maybe you do? Here."

**Comment by djencks** [comment]
@mojavelinux My whole aim here has been that when something unexpected happens to show the user what that was, and something about how it's unexpected, so they have a chance to figure out what is wrong, and perhaps submit an informative bug.  In Ec Roc's case, seeing the original line immediately led to a solution to the problem.

BTW perhaps the response Ec Roc got should be expected, I think the regular git client reports something similar to me when I try to push a branch to the antora or isomorphic git repo rather than my fork.  I haven't really investigated however.

@wmhilton I modified my branch to restore informative exception contents (the expected line should be a description of what we expected, e.g., "two strings separated by ' '", not the separator character itself) and to  use Ec Roc's observed server output in the \0 test.  I think this produces reasonable if not ideal output from the sorts of unparseable input I can imagine going into the method.  You can clearly see the line that was unparseable, and draw your own conclusions; in Ec Roc's case, the conclusion was obvious.

Trying the same tests on William's https://github.com/isomorphic-git/isomorphic-git/pull/924, no exceptions are thrown at all, wholly concealing the existence of any problem:
```
  ● git wire protocol › parseRefsAdResponse bad null separated

    Failed: "expected an error"

      210 |         service: 'git-upload-pack'
      211 |       })
    > 212 |       fail('expected an error')
          |       ^
      213 |     } catch (error) {
      214 |       expect(error.code).toEqual(E.AssertServerResponseFail)
      215 |       expect(error.data).toEqual({

      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:778:61)
      at Object.fail (__tests__/test-wire.js:212:7)

  ● git wire protocol › parseRefsAdResponse HEAD bad space separated

    Failed: "expected an error"

      241 |         service: 'git-upload-pack'
      242 |       })
    > 243 |       fail('expected an error')
          |       ^
      244 |     } catch (error) {
      245 |       expect(error.code).toEqual(E.AssertServerResponseFail)
      246 |       expect(error.data).toEqual({

      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:778:61)
      at Object.fail (__tests__/test-wire.js:243:7)

  ● git wire protocol › parseRefsAdResponse refs bad space separated

    Failed: "expected an error"

      267 |         service: 'git-upload-pack'
      268 |       })
    > 269 |       fail('expected an error')
          |       ^
      270 |     } catch (error) {
      271 |       expect(error.code).toEqual(E.AssertServerResponseFail)
      272 |       expect(error.data).toEqual({

```
To me this is not an acceptable resolution of the original problem.  It's worse than the original situation, where Antora at least could identify the line in isomorphic-git where the problem was concealed and we could work backwards to figure out what was going on.

**Comment by mojavelinux** [comment]
@djencks I don't think we're disagreeing. If the line is malformed, isomorphic-git should throw an error saying so and preserve the line so that it can be inspected.

While the error Ec got was a permission error, it was not sent by the server in the correct way. A permission error should be a 403 error. Instead, the server returned a 200 status and stuffed the error message into the body. In that case, isomorphic-git should simply say "no way, that's a bad response" and then pass that response along as the exhibit.

**Comment by wmhilton** [comment]
> My whole aim here has been that when something unexpected happens to show the user what that was, and something about how it's unexpected, so they have a chance to figure out what is wrong, and perhaps submit an informative bug. In Ec Roc's case, seeing the original line immediately led to a solution to the problem.

It seems to me the thing that would have helped the most would have been to include the entire response, or all the unparseable parts. I'm not sure reporting which individual part of the parsing (e.g. "I expected a \0 byte here") are useful. Certainly to create a test case it's more useful to have the whole response.

I'm tempted to go with a more general `E.UnparseableServerResponseFail` that includes a wide selection of the response (maybe the first few hundred characters) in the error message.

**Comment by wmhilton** [comment]
(and the full data of the response in `error.data.response` or something)

**Comment by djencks** [comment]
My proposal does include the entire unparseable line.  While not particularly useful in the particular case Ec Roc found, indicating why the response is unparseable could be useful if for instance a line arrives with two adjacent spaces instead of one.
Including the entire response or the response up to and including the problem part would be great, but I don't immediately see how to do that efficiently.  If the error occurs on the 1500th ref the first few hundred characters wouldn't include it.  Having a special error seems like a great idea.
How about including the bad line in the message along with the problem, and the entire response in error.data.response?  If it's something like a double space, it's going to be much easier to see if you know what line it's in.

**Comment by wmhilton** [comment]
@djencks Just reviewed your updated PR and I really like it!

> How about including the bad line in the message along with the problem, and the entire response in error.data.response?

Argh I'm just now realizing that's a little difficult to do because the parser is a streaming parser. How about for now we stick with the PR you've made?

**Comment by djencks** [comment]
Aha! No wonder I didn't see how to show the whole message :-)  I still like my PR!

**Comment by wmhilton** [comment]
@djencks You're PR saved the day today! My boss said "we're getting this weird `'split' of undefined` error when we try to push to Bitbucket..." and I was like "lemme stop you there, try upgrading to the latest version." And he said, "Oh! That's a much better error message!"

![image](https://user-images.githubusercontent.com/587740/68445479-0815c780-01a8-11ea-82d7-e284986dcdc7.png)

**Comment by mojavelinux** [comment]
Awesome! Now that's how you impress the boss ;)
